### ISSUE TITLE
List down manual validations

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-js#10]
The JSON Schema version of the spec is capable of validating many things, however, many others are impossible or very complicated to express. We should carefully read the spec and create a list of all the restrictions/validations that should be applied aside from the JSON Schema ones.

## List

- [~~Message examples are valid messages. Not sure if ajv is performing this validation on the schema `examples`~~](https://github.com/asyncapi/parser-js/issues/99)
- [~~Server variable examples are valid according to the schema.~~](https://github.com/asyncapi/parser-js/issues/100)
- Operation Ids are unique.
- Check that a server security scheme name matches an object on components/securitySchemes.

**Comment by derberg** [comment]
Are we doing it in parser or that should go to linters?

channel params is a similar use case that I had with server variables.
Would be good to draw a clear line of what is part of parser validation and what should be implemented separately 😄 

Or maybe we should produce some doc that describes all possible validations :thinking: a kind of reference that would be very handy for those that create validators in different languages...

**Comment by derberg** [comment]
it is related partially to #24

**Comment by fmvilas** [comment]
> Are we doing it in parser or that should go to linters?

I think the case I describe above should be here in the parser but I understand it's a thin line. I think it's wrong to say that there's a parameter but it's not defined anywhere. However, the opposite might be fine for the linter: there's a defined parameter that's not used. What do you think?

> Or maybe we should produce some doc that describes all possible validations

You just described the TCK: Give it a try on [this branch](https://github.com/asyncapi/tck/pull/1).

**Comment by derberg** [comment]
@fmvilas 

> Message examples are valid messages. Not sure if ajv is performing this validation on the schema examples.

If you mean [`examples`](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.5) than no, Ajv doesn't want to do it, but it can be done with Ajv plugin, all details [here](https://github.com/ajv-validator/ajv/issues/962#issuecomment-469038167). I did not find any available plugin at the moment.
Knowing that Ajv is now under development to support latest JSON Schema, and it affects Ajv architecture as the plan is to rewrite with TypeScript, I suggest we create a separate issue for it and not in the scope of Parser 1.0 release

> Server variable examples are valid according to the schema.

What do you mean by `schema`? There is [no schema for server variables](https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-servervariableobject-a-server-variable-object). I don't think we can actually validate those examples really as at the end it is all string

> Operation Ids are unique

> Check that a server security scheme name matches an object on components/securitySchemes.

I'll work on those 2 but first I need to have https://github.com/asyncapi/parser-js/pull/91 merged as this is a first-time manual validation is introduced and I want to be sure this is the way to go

**Comment by fmvilas** [comment]
> I suggest we create a separate issue for it and not in the scope of Parser 1.0 release

👍 

> What do you mean by schema? There is no schema for server variables. I don't think we can actually validate those examples really as at the end it is all string

Sorry, my fault. However, we can still validate against the `enum` property if present.

**Comment by derberg** [comment]
issue for message examples https://github.com/asyncapi/parser-js/issues/99
issue for server variables examples https://github.com/asyncapi/parser-js/issues/100

**Comment by derberg** [comment]
Reopen as we still need to fix `Check that a server security scheme name matches an object on components/securitySchemes.` 

above release just contains `Operation Ids are unique.` part
