### ISSUE TITLE
Add validation of server variable example

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#100]
#### Reason/Context
You can provide in the AsyncAPI document a variable used in the server URL, later you describe such a variable with https://www.asyncapi.com/docs/specifications/2.0.0/#a-name-servervariableobject-a-server-variable-object and one of the supported fields is `example` that we should validate

#### Description
validate variable example against the enum value. In case there is no `enum` we should not fail validation but if the `enum` is there and the example is not one of the values from the `enum`, validation should fail

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=1528

**Comment by DanielChuDC** [comment]
Hello, @derberg I am interested in this issue. I took some time and dig the code. Would like to ask for your suggestion about my solution.

`file directory: lib --> server-variable.js`, inside have include the function to parsing example variables.

```
# example

  /**
   * @returns {string[]}
   */
  examples() {
    return this._json.examples;
  }
```


I am thinking to add some if else statement to judge the value is define within enum. If found enum specification and the value does not match one of the enum values, throw error. From line 55- 60 ,according to the picture below. Do you think I am pointing to correct direction?

<img width="1484" alt="Screenshot 2020-12-30 at 12 48 10 AM" src="https://user-images.githubusercontent.com/52316624/103300184-4370f680-4a39-11eb-9b95-3d98f0f357e1.png">

**Comment by derberg** [comment]
@DanielChuDC hey, welcome back, awesome you stayed after the Hacktoberfest 🥳 

The validation of the server variables' examples must happen sooner than `server-variable.js`. The code you mention belongs to the object that is the output of the parsing. Validation must happen before parsing is finished. All custom validators are here https://github.com/asyncapi/parser-js/blob/master/lib/customValidators.js. The best would be to extend this validator https://github.com/asyncapi/parser-js/blob/master/lib/customValidators.js#L13, I mean add some custom function that validates examples and is invoked inside `validateServerVariables`

**Comment by DanielChuDC** [comment]
Hi @derberg , I have modified the code.

```

/**
 * Validates if variables provided in the url have corresponding variable object defined
 * @private
 * @param  {Object} parsedJSON parsed AsyncAPI document
 * @param  {String} asyncapiYAMLorJSON AsyncAPI document in string
 * @param  {String} initialFormat information of the document was oryginally JSON or YAML
 * @returns {Boolean} true in case the document is valid, otherwise throws ParserError
 */
function validateServerVariables(
  parsedJSON,
  asyncapiYAMLorJSON,
  initialFormat
) {
  const srvs = parsedJSON.servers;
  if (!srvs) return true;

  const srvsMap = new Map(Object.entries(srvs));
  const notProvidedVariables = new Map();
  const notProvidedEnumInExamples = new Map();

  srvsMap.forEach((val, key) => {
    const variables = parseUrlVariables(val.url);
    const notProvidedServerVars = notProvidedVariables.get(tilde(key));
    if (!variables) return;

    const missingServerVariables = getMissingProps(variables, val.variables);
    if (!missingServerVariables.length) return;

    notProvidedVariables.set(
      tilde(key),
      notProvidedServerVars
        ? notProvidedServerVars.concat(missingServerVariables)
        : missingServerVariables
    );

    const enumExamples = val.variables;
    const enumExamplesMaps = new Map(Object.entries(enumExamples));
    enumExamplesMaps.forEach((val, key) => {
      if (val.enum && val.examples) {
        const missingEnumVariablesInExamples = getMissingProps(
          val.Enum,
          val.example
        );
        if (!missingEnumVariablesInExamples.length) return;

        const notProvidedEnumInExamples = notProvidedVariables.get(tilde(key));
        notProvidedEnumInExamples.set(
          tilde(key),
          notProvidedEnumInExamples
            ? notProvidedEnumInExamples.concat(missingEnumVariablesInExamples)
            : missingEnumVariablesInExamples
        );
      }
    });
  });

  if (notProvidedVariables.size) {
    throw new ParserError({
      type: validationError,
      title: "Not all server variables are described with variable object",
      parsedJSON,
      validationErrors: groupValidationErrors(
        "servers",
        "server does not have a corresponding variable object for",
        notProvidedVariables,
        asyncapiYAMLorJSON,
        initialFormat
      ),
    });
  }

  if (notProvidedEnumInExamples.size) {
    throw new ParserError({
      type: validationError,
      title:
        "Please check your server variables. The example value is not one of the values from the enum.",
      parsedJSON,
      validationErrors: groupValidationErrors(
        "servers variables",
        "server does not have a corresponding variable object for",
        notProvidedEnumInExamples,
        asyncapiYAMLorJSON,
        initialFormat
      ),
    });
  }

  return true;
}
```

Added a function.

Will this code works?

Cannot test on it due to #220 .

**Comment by DanielChuDC** [comment]
hehe I manage to fix it! on branch https://github.com/DanielChuDC/parser-js

But the documentation job run is failed. What should I do?

**Comment by derberg** [comment]
@DanielChuDC the best would be if you could open a PR, this is much easier for me to review and interact with code. We will also clearly see what CI has to say while checking the PR. Don't worry you are not 100% sure if PR is correct or not, it is ok to reiterate on a PR

**Comment by DanielChuDC** [comment]
Thank you @derberg . The pull request has been created!
