### ISSUE TITLE
[Bounty] A bunch of bugs that can be completed through the Bounty program

### ISSUE THREAD

**Issue by smoya** [asyncapi/parser-js#1012]
### Describe the bug
The completion of **all** of the following bugs can be considered as completing a single Bounty Program issue of `medium` complexity level :

- [x] https://github.com/asyncapi/parser-js/issues/980
- [x] https://github.com/asyncapi/parser-js/issues/936

**Comment by smoya** [comment]
> I would like to work on this issue within the Bounty Program.

A pleasure. Assigned to you @aeworxet

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q3`, `bounty/medium`, `bounty/coding`
First assignment to third-party contributors: [2024-06-21 00:00:00 UTC+12:00](https://time.lol/#2024-06-21T00:00:00+12:00)
End Of Life after: [2024-07-31 23:59:59 UTC-12:00](https://time.lol/#2024-07-31T23:59:59-12:00)

@asyncapi/bounty_team

##### The Bounty Program is not a Mentorship Program. The accepted level of Bounty Program Participants is **Middle**/**Senior**.
##### Third-party contributors should [coherently articulate](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2119226365) how they are going to approach the resolution process when expressing a desire to work on this Bounty Issue.

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)**        |[2024-07-14](https://time.lol/#2024-07-14T23:59:59-12:00)         |[2024-07-28](https://time.lol/#2024-07-28T23:59:59-12:00)         |**[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
@ramishj
Law enforcement in your area was notified about your attempt to unauthorizedly use the `/bounty` command.

**Comment by aeworxet** [comment]
No PRs have been submitted yet; a code investigation is ongoing.

https://github.com/asyncapi/parser-js/issues/980#issuecomment-2227599634

https://github.com/asyncapi/parser-js/issues/936#issuecomment-2230286333

**Comment by aeworxet** [comment]
To [lay the foundation](https://github.com/asyncapi/parser-js/issues/980#issuecomment-2227599634) for fixing https://github.com/asyncapi/parser-js/issues/980, PR https://github.com/stoplightio/spectral/pull/2658 was submitted to https://github.com/stoplightio/spectral, so the Timeline of this Bounty Issue is frozen until that PR is merged.

**Comment by aeworxet** [comment]
AsyncAPI Maintainer (@jonaslagoni) delayed response for one period of three consequent working days
https://github.com/asyncapi/parser-js/issues/936#issuecomment-2238159672
https://github.com/asyncapi/parser-js/issues/936#issuecomment-2254103177
so all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |[2024-07-14](https://time.lol/#2024-07-14T23:59:59-12:00)         |[2024-08-11](https://time.lol/#2024-08-11T23:59:59-12:00)         |**[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
## Update

- https://github.com/asyncapi/parser-js/issues/980
  - fixed in both [`studio`](https://studio.asyncapi.com) and [`studio-next`](https://deploy-preview-1125--studio-next.netlify.app)

- https://github.com/asyncapi/parser-js/issues/936
  - submitted a PR https://github.com/asyncapi/parser-js/pull/1044, which is step 1 of 2 in fully fixing this bug for `Studio`

**Comment by aeworxet** [comment]
## UPDATE

- https://github.com/asyncapi/parser-js/issues/980
  - fixed in both [`studio`](https://studio.asyncapi.com) and [`studio-next`](https://deploy-preview-1125--studio-next.netlify.app)

- https://github.com/asyncapi/parser-js/issues/936
  - submitted a PR https://github.com/asyncapi/studio/pull/1126, which is step 2 of 2 in fully fixing this bug for `Studio`

**Comment by aeworxet** [comment]
PR https://github.com/asyncapi/studio/pull/1126 with the final fix of https://github.com/asyncapi/parser-js/issues/936 for `Studio` was submitted on 2024-08-05 and is still waiting for a review.

**Comment by aeworxet** [comment]
Response, critical for technical resolution of this Bounty Issue (**review of the [PR](https://github.com/asyncapi/studio/pull/1126)**) was delayed for one period of three consecutive working days
https://github.com/asyncapi/studio/pull/1126#issue-2447431379
https://github.com/asyncapi/studio/pull/1126#pullrequestreview-2235346733

so all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment Date (by GitHub)|Start Date (by BP Rules)|End Date (by BP Rules)|Draft PR Submission|Final PR Merge Start|Final PR Merge End|
|----------------|---------------------------|------------------------|----------------------|-------------------|--------------------|------------------|
|Medium          |2024-06-17                 |[2024-07-01](https://time.lol/#2024-07-01T00:00:00+12:00)              |**[2024-09-08](https://time.lol/#2024-09-08T23:59:59-12:00)**        |[2024-07-14](https://time.lol/#2024-07-14T23:59:59-12:00)         |[2024-08-25](https://time.lol/#2024-08-25T23:59:59-12:00)         |**[2024-09-08](https://time.lol/#2024-09-08T23:59:59-12:00)**        |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR218) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR105).

**Comment by aeworxet** [comment]
The last PR for this Bounty Issue [was merged](https://github.com/asyncapi/studio/pull/1126#event-13869151496) on 2024-08-14, and since that time I'm waiting for confirmation of the technical resolution of this Bounty Issue.

**Comment by smoya** [comment]
I confirm the issue is solved now.

**Comment by aeworxet** [comment]
### Bounty Issue Is Completed 🎉

@aeworxet, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 200.00` with the expense title `Bounty parser-js#1012`, tag `bounty`, and full URL of this Bounty Issue in the description.

**Comment by aeworxet** [comment]
## SUMMARY

- https://github.com/asyncapi/parser-js/issues/980
  - **Fixed in both [`studio`](https://studio.asyncapi.com) and [`studio-next`](https://deploy-preview-1126--studio-next.netlify.app).**
    PRs:
      - https://github.com/stoplightio/spectral/pull/2658 (third-party repository)
      - https://github.com/asyncapi/parser-js/pull/1042 (internal repository)
      - https://github.com/asyncapi/studio/pull/1124 (internal repository)

- https://github.com/asyncapi/parser-js/issues/936
  - **Fixed in both [`studio`](https://studio.asyncapi.com) and [`studio-next`](https://deploy-preview-1126--studio-next.netlify.app).**
    PRs:
      - https://github.com/asyncapi/parser-js/pull/1044 (internal repository)
      - https://github.com/asyncapi/studio/pull/1126 (internal repository)
