### ISSUE TITLE
@asyncapi/parser doesn't work in browser

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/parser-js#123]
#### Describe the bug

I created a new `react` app and add in dependencies `@asyncapi/parser`. Making example as in Readme.md I see the error:

```bash
Module not found: Can't resolve './build/Release/re2'
``` 

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

Create any browser app, but I give react example:
- `npx create-react-app my-app`
- `cd my-app && npm i @asyncapi/parser`
- change main `App.js` component to:

```js
import { parse } from "@asyncapi/parser";

function App() {
  useEffect(() => {
    const lol = async () => {
      const doc = await parse(`
        asyncapi: '2.0.0'
        info:
          title: Example
          version: '0.1.0'
        channels:
          example-channel:
            subscribe:
              message:
                payload:
                  type: object
                  properties:
                    exampleField:
                      type: string
                    exampleNumber:
                      type: number
                    exampleDate:
                      type: string
                      format: date-time
      `);
      const channels  = doc.channels();
      console.log(channels);
    }
  });

  return null;
}
```

- you should see error, which is mentioned in description of bug.

#### Expected behavior

Parser should works in node and in browser without errors.

#### Possible solution

Use native Regex, not `Re2`, because it has a compiled binary, and also investigate if `node-fetch` could problems running on browser.

**Comment by derberg** [comment]
crap, I went too far with sonarcube recommendations, forgot about the browser
`Re2` is not a must, but we need to make sure we mitigate a security issue

root of the issue is that bundle is not updated at all, and now it is empty in the master:
```
$ npm run prepublishOnly

> @asyncapi/parser@0.26.0 prepublishOnly /Users/wookiee/Documents/sources/parser-js
> npm run bundle


> @asyncapi/parser@0.26.0 bundle /Users/wookiee/Documents/sources/parser-js
> browserify lib/browser.js | uglifyjs > dist/bundle.js

Error: Cannot find module './build/Release/re2' from '/Users/wookiee/Documents/sources/parser-js/node_modules/re2'
    at /Users/wookiee/Documents/sources/parser-js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/wookiee/Documents/sources/parser-js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/wookiee/Documents/sources/parser-js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/wookiee/Documents/sources/parser-js/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:166:21)
```

---
regarding `node-fetch`, I hope browserify is smart and replaces it with native fetch for a browser (wishful thinking 😄 )

**Comment by derberg** [comment]
anyway, I added it to the scope of 1.0 release

**Comment by MikeRalphson** [comment]
You might want something like https://github.com/lquixada/cross-fetch

**Comment by derberg** [comment]
`node-fetch` is not a problem because of https://github.com/asyncapi/parser-js/blob/master/package.json#L68 that makes `node-fetch` => `window.fetch` so `cross-fetch` is not needed
