### ISSUE TITLE
Extract checkErrorWrapper and use it in other tests

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#140]
#### Reason/Context
Tests that do `try/catch` to evaluate thrown error must be wrapped in `checkErrorWrapper` to make sure tests always work, and they fail even if the test doesn't jump into the `catch`.

#### Description
- move `checkErrorWrapper` from `parse_test.js` to separate file, `utils.js` ?
- refactor `asyncapiSchemaFormatParser_test.js` and `customValidators_test.js` to use wrapper in test cases where `try/catch` is used

**Comment by McZenith** [comment]
Hi! I would like to grab this...

**Comment by derberg** [comment]
@McZenith awesome, I'll assign to you. If you need real-time help/advice you can also join https://www.asyncapi.com/slack-invite/ and find be there on #tooling channel

**Comment by McZenith** [comment]
@derberg Thank you, Updates soon...

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=1649

**Comment by derberg** [comment]
@McZenith are you still working on this? pr just got closed by the stale bot

**Comment by derberg** [comment]
closed with https://github.com/asyncapi/parser-js/pull/251
