### ISSUE TITLE
Add validation of duplicated tags

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#143]
#### Reason/Context
We need to validate if users did not provide 2 tags with the same name on the same level. Tags can be provided in many objects, we should avoid duplicates only in a given object not across the whole document.

#### Description
- I don't think we can do it with JSON Schema. I found something like https://groups.google.com/forum/#!topic/json-schema/z34YqedG-1s but it won't work for us as we use ` "additionalProperties": false`
> https://json-schema.org/understanding-json-schema/reference/combining.html
Unfortunately, now the schema will reject everything. This is because the Properties refers to the entire schema. And that entire schema includes no properties, and knows nothing about the properties in the subschemas inside of the allOf array.
This shortcoming is perhaps one of the biggest surprises of the combining operations in JSON schema: it does not behave like inheritance in an object-oriented language. There are some proposals to address this in the next version of the JSON schema specification.

- we need to add a custom validation of tags wherever tags are possible
- example files that have duplicates but the parser doesn't throw an error:
  - https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Operation%20Object/invalid-duplicate-tags.yaml
  - https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/AsyncAPI%20Object/invalid-duplicate-tags.yaml
  - https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Message%20Object/invalid-duplicate-tags.yaml
  - https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Message%20Trait%20Object/invalid-duplicate-tags.yaml
  - https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Operation%20Trait%20Object/invalid-duplicate-tags.yaml

**Comment by arjungarg07** [comment]
I am currently getting familiar with the codebase of `parser-js` and would like to give this issue a try soon.

**Comment by derberg** [comment]
@arjungarg07 still interested?

**Comment by arjungarg07** [comment]
@derberg Currently working on #265, would love if someone can follow up on this for now.

**Comment by BOLT04** [comment]
Hi everyone 👋, is anyone working on this issue? if no one is working on it I'd like to contribute and give it a try 🙂.

@derberg I'm new to this codebase so could you tell me some details on where this issue touches? I did some digging and found the `lib/customValidators.js` file, so I'm guessing to pass the requirement "we need to add a custom validation of tags wherever tags are possible" we'd need to modify this file. This is used in the `parser.js` in this function:
https://github.com/asyncapi/parser-js/blob/e8c72d781792d2bb8ea5f907251f3b1f5470b695/lib/parser.js#L178

I was thinking if we could simply modify the `validateChannels` function, adding code to validate if there are duplicate tags, something like this:
```js
chnlsMap.forEach((val, key) => {
    // ...
    Object.keys(val).forEach((channelOperation) => {
      const valueArr = val[channelOperation].tags.map(item => item.name);
      const hasDuplicateTags = valueArr.some((item, idx) => valueArr.indexOf(item) != idx);
      
      if (hasDuplicateTags) {
        throw new ParserError({
          type: validationError,
          title: `Invalid channel \"${channelOperation}\", there can't be any duplicate tags`,
          parsedJSON,
          validationErrors: groupValidationErrors(
            'channels',
            'channels contains duplicate tags',
            new Map(), // TODO: Not sure what would go here
          ),
        });
      }
    });
  });
```

> I don't think we can do it with JSON Schema. 

Does this refer to the `parsedJSON` parameter of the `validateChannels` function, for example? If it does, can you explain further why we can't use it?

I was also thinking we should add some test cases in the `parse_tests.js` file and perhaps `tags_test.js`, what do you think? Would it be possible to use the examples from `asyncapi/tck`?

Feel free to give me any feedback on what I suggested, I could be looking at this issue completely wrong 😅

**Comment by magicmatatjahu** [comment]
@BOLT04 Hi! Yes, you're thinking right about place where new code for validation should be :) 

> I don't think we can do it with JSON Schema.

Refers to the plain JSON Schema (https://json-schema.org/), not to our Schema (in the meaning of AsyncAPI), so of course you can use `parsedJSON`, because it is exactly AsyncAPI document saved as JSON :)

> I was also thinking we should add some test cases in the parse_tests.js file and perhaps tags_test.js, what do you think? Would it be possible to use the examples from asyncapi/tck?

Yes, tests will be needed, if you want you can use the test cases from tsk. We have issue to use all cases from tck, but not now so feel free to use them.

Also, please have in mind that `tags` don't occur only in `channels` (to be precise in the `publish` | `subscribe` fields) but also in the other parts of AsyncAPI spec:
- in root of doc
- in Operation (`subscribe` | `publish`) object
- in OperationTrait object
- in Message Object
- in MessageTrait Object

so probably running validation in the `validateChannels` won't be enough.

Also, your example solution is good 👍🏼  Go ahead if you want with implementation :)

**Comment by BOLT04** [comment]
@magicmatatjahu would it be better to add a `validateTags` function with all those places `tags` can occur, like this:
```diff
async function customDocumentOperations(parsedJSON, asyncapiYAMLorJSON, initialFormat, options) {
  validateServerVariables(parsedJSON, asyncapiYAMLorJSON, initialFormat);
  validateServerSecurity(parsedJSON, asyncapiYAMLorJSON, initialFormat, SPECIAL_SECURITY_TYPES);

  if (!parsedJSON.channels) return;

+ validateTags(parsedJSON, asyncapiYAMLorJSON, initialFormat);
  validateChannels(parsedJSON, asyncapiYAMLorJSON, initialFormat);
  validateOperationId(parsedJSON, asyncapiYAMLorJSON, initialFormat, OPERATIONS);

  await customComponentsMsgOperations(parsedJSON, asyncapiYAMLorJSON, initialFormat, options);
  await customChannelsOperations(parsedJSON, asyncapiYAMLorJSON, initialFormat, options);
}
```

or modify the existing validate functions and create new ones if they don't exist (e.g. I didn't find validation for OperationTrait)?

**Comment by magicmatatjahu** [comment]
@BOLT04 `validateTags` is better idea than update existing :)
