### ISSUE TITLE
YAML empty objects are null in JSON and cause parser errors

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#144]
#### Describe the bug
Such AsyncAPI file is not valid
```
asyncapi: 2.0.0

info:
  title: Signup service example (internal)
  version: 0.1.0

channels:
  /user/signedup:
    subscribe:
```
and it is because when parsed to json, `subscribe` is NULL and ajv-validator or json-ref-parser (in other cases) fail.

#### How to Reproduce
Just paste [this](https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Operation%20Object/valid-empty-object.yaml) doc in the playground and you will see it will throw errors

#### Expected behavior
Parser should work fine with valid YAML files

**Comment by fmvilas** [comment]
That is a correct behavior. To indicate an empty object in yaml use `{}`.

**Comment by derberg** [comment]
@fmvilas then https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Channel%20Item%20Object/valid-empty-object.yaml and https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Operation%20Object/valid-empty-object.yaml need to be fixed with `{}` or switched to invalid and called like `invalid-null-object`

**Comment by fmvilas** [comment]
Yep. These have to be fixed.
