### ISSUE TITLE
Add validation of query params in channel name

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#145]
#### Reason/Context
channel should not contain query parameters. The parser should throw a validation error once a query param is spotted.

#### Description
- add validation and test it against such an example https://github.com/asyncapi/tck/blob/master/tests/asyncapi-2.0/Channels%20Object/invalid-query-param-used.yaml

**Comment by fmvilas** [comment]
You mean **channels** should not have query params, right?

**Comment by derberg** [comment]
@fmvilas ups, yes 😄

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=1807

**Comment by juergenbr** [comment]
I would like to work on this issue.
In my fork you can find a solution proposal, containing a new validator and test suite.
https://github.com/juergenbr/parser-js

**Comment by derberg** [comment]
@juergenbr can you open a PR please, will be much easier to work this way. You can mark it as a draft if you want, but there is no need for this from my side
