### ISSUE TITLE
Throw meaningfull error when parser of specific schemaFormat is not available

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#157]
#### Describe the bug
We do not check if there is a parser available for a given custom `schemaFormat` and throw not meaningful error that `PARSERS[String(...)] is not a function`

Hint: this is where we trigger parsers and we need to validate if the function is really there -> https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L179

#### How to Reproduce
Just try to parse the spec with payload defined with some openapi/raml/avro schema. Without registering schema parsers for those schema formats.

#### Expected behavior
In my opinion we need to add new error type and document it in the readme too https://github.com/asyncapi/parser-js#error-types

How about: `schema-parser-not-registered`? with `detail` property that indicates exactly what message has this problem? and of course exact location of the error in the file.

Bonus would be to have an idea how to tell the user that for some schemas there are parsers, and where they can find them

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=1857

**Comment by ritik307** [comment]
Hi @derberg I would like to work on this issue

**Comment by derberg** [comment]
@ritik307 go ahead man, make sure to look into previous PR, there was already a lot of work done that you can reuse afaik

**Comment by ritik307** [comment]
> @ritik307 go ahead man, make sure to look into previous PR, there was already a lot of work done that you can reuse afaik

Sure will look into them 😁

**Comment by ritik307** [comment]
@derberg I am facing an error while setting up the project to the point where the last PR was made. I have added everything that was done the last PR. While testing the code after completing the changes I face the following issue:- 

![ss1](https://user-images.githubusercontent.com/22374829/149956160-410c6764-4cbd-40c3-9dca-0fb1a4ad872a.png)

I replaced it with the `defaultSchemaFormat` function and all my test cases passed.

![ss1](https://user-images.githubusercontent.com/22374829/149956382-d3e3089c-a312-4771-a056-a510b43e004b.png)


So is it the correct way to resolve the error or am I doing something wrong here?

**Comment by derberg** [comment]
@ritik307 please open up a `Draft` PR as it will be much easier to see all the changes that you did and ineract there on specifics 🙏🏼

**Comment by magicmatatjahu** [comment]
Issue is resolved in v2 ParserJS - now in https://github.com/asyncapi/parser-js/tree/next-major branch in https://github.com/asyncapi/parser-js/blob/next-major/src/schema-parser/index.ts#L34 line - but we need probably wait for PR for v1 ParserJS https://github.com/asyncapi/parser-js/pull/449

What do you think, should we close it or should we wait for https://github.com/asyncapi/parser-js/pull/449 PR?

cc @derberg @ritik307

**Comment by derberg** [comment]
up to @ritik307 if he can continue. Otherwise close I guess

**Comment by magicmatatjahu** [comment]
Ok @ritik307 I will wait max 2 weeks for your response and in the case without response I will close this one.

**Comment by magicmatatjahu** [comment]
I am closing due to lack of response.
