### ISSUE TITLE
Auto generating the parser

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#170]
### Reason/Context
I love code generation, it makes it so much easier to create libraries and I feel like we can utilize this in the parser by utilizing the [machine readable files](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json) which are written in JSON Schema draft 7. This means we would have to create a parser, generator and parser template for JSON Schema draft 7.

My reason for **why we should** take this approach

1. We already have multiple version of the machine readable file of AsyncAPI and could provide tools to all these version.
2. We can utilize the CI to automate code changes way more than we currently are, meaning we would only need to change the machine readable file to change the tool versions 🤯 
3. With this approach we will contribute to the JSON Schema organization and provide tools that can be used to other use cases then the parser (Read the description for what I mean about this).
5. We already have the tools (parser and [generator](https://github.com/asyncapi/generator)) which with very little modification can support this.

### Description
I would not suggest using any of the existing tools listed on the [JSON Schema website](https://json-schema.org/implementations.html), I have used quite a few of the tools there, and AFAIK nothing comes close to supporting the use-case we require.

**How I suggest to adapt the parser and generator to JSON Schema draft 7**

For the copy of the parser this means only utilizing the [schema model](https://github.com/asyncapi/parser-js/blob/master/lib/models/schema.js) and strip everything away in regards to AsyncAPI (maybe only have 1 parser where you supply it with external parsers like what is done with the schema parsers?).

For the generator it gets a bit more complicated, should we create a copy of the generator and adopt it towards the JSON Schema draft 7 parser or would it be silly to have 2 generators which have very similar code structure not share code somehow? Could a general generator be an option?

For the parser template the most tricky things to handle are the properties `allOf`, `anyOf`, `oneOf`, `additionalProperties`, `patternProperties` etc when they are nested. Example just look at [the operation traits definition](https://github.com/asyncapi/asyncapi/blob/e2921d50e23a5ddb3cdb5e4ebd188292c07baf9a/versions/2.0.0/schema.json#L544-L575), this was at least what I had the most problems with wrapping my head around how to actually template such definitions last time I did it. So as much as possible use the current parser implementation as a reference point.

### Drawbacks and mitigation 

Some of the drawbacks I see and how to mitigate it.
1. More complicated for newcomers to contribute, as the complexity of code generation increases newcomers will have a harder time to understand and know where to help out and how everything works together. To **mitigate** this I would suggest to make it an integrated part of the website i.e. create detailed (visual?) guide to how to contribute to our tools, which gives the developer far more information then a simple contribution guide line in the repository.
2. Templating JSON Schema draft 7 requires very high knowledge of JSON Schema, this will by far be the biggest hurdle to handle in this transition. I can however not see any way of mitigating this.

### Furthermore
Where could this also be used? Automate parts of the [API descriptions on the website](https://www.asyncapi.com/docs/specifications/2.0.0/) with the description attribute?

**Comment by derberg** [comment]
@jonaslagoni I have few questions:

> We already have multiple version of the machine readable file of AsyncAPI and could provide tools to all these version.

what multiple versions you have in mind? there should be one, unless you mean that now we have more as we keep it in different locations?

> I would not suggest using any of the existing tools listed on the JSON Schema website

you mean quicktype is not good enough?
---

It would not be too difficult to make AsyncAPI Generator a AsyncAPI/OpenAPI/JSONSchema/WhateverElseInTheFuture Generator. So technically it is not bad, I actually talked to Fran about it one day, that we can have more generic generator.

What parts of the JavaScript parser would you like to generate? I guess models and the rest would be static? And by parsers generation, you mean generation of parsers for different languages, just like we do with templates for AsyncAPI?

**Comment by jonaslagoni** [comment]
> what multiple versions you have in mind? there should be one, unless you mean that now we have more as we keep it in different locations?

@derberg what I mean by multiple version is that the parser should support version 1, 2 and all in between and future version of the AsyncAPI specification. 

> What parts of the JavaScript parser would you like to generate? I guess models and the rest would be static?

Yes that would probably be the case. 


>  And by parsers generation, you mean generation of parsers for different languages, just like we do with templates for AsyncAPI?

Yes :smile:

**Comment by derberg** [comment]
@jonaslagoni you still with the idea? looks like it is connected with current work on data model generation

**Comment by jonaslagoni** [comment]
> @jonaslagoni you still with the idea? looks like it is connected with current work on data model generation
I would say so yes. However it will be some time until we can implement it 😄

**Comment by derberg** [comment]
@jonaslagoni I'm more concerned by `complexity`. I mean this is not a task that takes 1day/week/month. It is a big one and needs many prerequisites. If we do not make the decision to go in this direction, it will not be solved for a few months 😄 

yeah, just wondering if it makes sense to keep it open 😉 of course keep open labels is a kind of option.

**Comment by jonaslagoni** [comment]
I mean this issue does relate to the bigger issue of how we want to handle the changes in the spec in our tools and how we can minimize the maintainers work as much as possible. 

I could convert this to a research pitch for a cycle instead, what you think @derberg ? 🤔

**Comment by derberg** [comment]
Could be, 3.0 will happen this year for sure, would be great to know how technically we can handle it in a more efficient way than we do it now
