### ISSUE TITLE
Package should allow create instance of parser

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/parser-js#178]
#### Reason/Context
- Why we need this improvement?

I have a mini project and I use parser-js, and I want to make logic in it, which would have a raml parser for one case and openapi for the other. However, the parser would throw an error in the raml parser that there is no openapi parser defined, and in the second that there is no raml parser defined. Currently, parsers are global, so if you use a parser once in your code and add custom scheme to it then this schema is global and it's break my idea in app.

In the current situation the package is mostly stateless, only the global parsers are kind of state.

#### Description
- What changes have to be introduced?

Create class `Parser` and wrap existing core functions in class and create common instance.

- Will this be a breaking change?

No. Only `parse`, `parseUrl` etc methods will be wrapped by exported common instance of parser, so the old code will still work -> see implementation.

- How could it be implemented/designed?

Very easy. Package will have a new class `Parser` and instance of it class will have this same methods like common parser, `parse()`, `parseUrl()`, `registerSchema()` etc.

```js
/**
 * Implements functions to deal with the AsyncAPI document. 
 * @class
 * @param {string} name - Name of the parser. For testing, error handling etc.
 * @returns {Parser}
 */
class Parser {
  constructor(name) {
    this.name = name;
    // custom schema parsers
    this.parsers = {};
  }

  async parse() {}
  async parseFromUrl() {}
  registerSchemaParser()
}

// parser instance for backward compatibility
const parser = new Parser("parser-js");
parser.registerSchemaParser(defaultAsyncAPISchemaParser);
export parser;
```

**Comment by derberg** [comment]
> However, the parser would throw an error in the raml parser that there is no openapi parser defined, and in the second that there is no raml parser defined.

when do you get this error? this is pretty strange I have to say

**Comment by magicmatatjahu** [comment]
@derberg I mean (sorry for misunderstanding), if I have a case where I need only parser for raml, and if someone use in this case asyncapi spec with e.g. openapi schema format, tne parser should throw error, than parser hasn't registered openapi parser, but in this same application I want to have another case, where parser has a registered openapi parser, and then if someone put spec with raml, parser should throw error about excluded custom parser.

**Comment by derberg** [comment]
for now, we do not throw any meaningful error if some schema parser is not available and this is what we have https://github.com/asyncapi/parser-js/issues/157 for

what is the real use case behind this idea, why would you like to have different instances of the parser with different custom schema parsers? what value it brings, why not have all the ones that you need always registered?

**Comment by magicmatatjahu** [comment]
One of the possible cases: https://github.com/asyncapi/asyncapi-react/pull/163#issuecomment-704898456

**Comment by derberg** [comment]
@magicmatatjahu how would it work with the react component? Also, I don't think classes are requirement for having a solution in the react component to register additional parsers
