### ISSUE TITLE
$ref doesn't work with multi-layer references, because working directory changes?

### ISSUE THREAD

**Issue by komodovaran** [asyncapi/parser-js#179]
#### Describe the bug
$ref doesn't work with e.g. A.yaml that refers to B.yaml, which refers to C.yaml. An example could be VerySpecific.yaml -> Generic.yaml -> Base.yaml.

I use this structure to generate C# classes as well.

#### How to Reproduce
1. Place yaml scripts in _/Directory_
2. A.yaml refers to B.yaml via $ref: '._/Directory/B.yaml_' and B.yaml refers to C.yaml via _/Directory/C.yaml_ 
3. Run generator with a relative reference to _/Directory_ as input directory
4. A.yaml can refer to B.yaml, but when B.yaml then refers to C.yaml, it says _/Directory/Directory/C.yaml_ does not exist.

The third reference can be "fixed" by removing _/Directory_ from $ref: '_Directory/C.yaml_. This, however, means that you can't run the generator directory on B.yaml directly, because it now has an "incorrect" working directory.

#### Expected behavior
$ref seems to change working directory in the scope of the function, and this breaks expected working directory references after one reference.

**Comment by derberg** [comment]
@komodovaran I moved it to the parser repo as it concerns parser itself.

What do you have in `B.yaml` that you would like to run a generator against this file? you mean you have references between different AsyncAPI files?

**Comment by derberg** [comment]
@komodovaran is it still valid?

**Comment by komodovaran** [comment]
Sorry for the slow pace.

I decided to forego this kind of file referencing entirely by simply splitting it into multiple files and merging them when they're being processed.

**Comment by derberg** [comment]
@komodovaran thanks for the confirmation
