### ISSUE TITLE
Disable PR testing if its a draft

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#200]
#### Reason/Context
Normally if I start working on a issue i create a draft PR as soon as I start so others know its being worked on. I normally also push changes to the branch quite frequently sometimes even when the code are not working or tests aren't going through, just to have a point in time I can go back to.

In that regard I don't find it useful to get emails or notifications that the tests are not working as long as its a draft.

#### Description
Something like `if: github.event.pull_request.draft == false` has to be added to the github action.

Edit:
Or something like `types: [review_requested, ready_for_review]`

**Comment by derberg** [comment]
makes sense I guess, I like the second proposal, just thinking why `review_requested` would be needed 🤔 do you know when `ready_for_review` is emitted? always except of draft?

**Comment by jonaslagoni** [comment]
`ready_for_review` is when [`pull request is taken out from draft mode`](https://frontside.com/blog/2020-05-26-github-actions-pull_request/). `review_requested` should only be used if we remove the `synchronize` event otherwise the test are not triggered when you open a PR in non-draft mode. 

The if statement may be more suited and giving us a bit more control since there are no `ready_for_review_synchronize` :smile: I would suggest we keep the current setup and add the if statement.

**Comment by derberg** [comment]
sure, I just prefered the other one as then action is just not triggered at all, but that is fine

**Comment by jonaslagoni** [comment]
Yea I agree. But if we do that we loose the ability to run actions on each change i.e. `synchronize` which I don't think we want right?

**Comment by derberg** [comment]
definitely, no objections to your proposal here, makes sense to me
