### ISSUE TITLE
Add ability to configure ssl certificate authentication to avro parser

### ISSUE THREAD

**Issue by rkling01** [asyncapi/parser-js#207]
I have an on premise implementation of the schema registry where it requires the ability to configure providing an ssl certificate for authentication (does not use key/secret authentication).  Would like to see if the ability to provide the location of the ssl certificate could be added to the AsyncAPI file to it can be passed in the uri fetch request in the message.payload.$ref.

**Comment by derberg** [comment]
We use `json-schema-ref-parser` and in their docs they specify that some custom resolver could be written https://apitools.dev/json-schema-ref-parser/docs/plugins/resolvers.html. We could enable users of the parsers to register a custom resolver. It is not something that would solve your issue but will enable you to solve it 😄 

We just need a way to let you pass an instance of the resolver to the parser before you start parsing, as simple as that 😄 
@fmvilas What do you think?

**Comment by fmvilas** [comment]
I think that we should be solving this issue ourselves, either by contributing to `json-schema-ref-parser` or creating a custom resolver ourselves. However, this is gonna take time so a middle-ground solution like you proposed would be great in the meantime.

**Comment by derberg** [comment]
The maintainers do not at the moment have time to implement it. But we so far agree the use case is valid and we need it. so whoever want's to work on it, just ping us here and we will be happy to guide you
