### ISSUE TITLE
No functions to access message and operation traits

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#226]
#### Reason/Context
Even though we provide access to message and operation traits if listed in the components sections, there exist no functions on the operation and message objects themselves to access traits if you use the parser with the option `applyTraits = false`. 

#### Description
I would expect functions such as the following to be available:
Message trait: `asyncapi.channel('mychannel').publish().message().traits();`
Operation trait: `asyncapi.channel('mychannel').publish().traits();`

It is possible to access the traits using the following
Message trait: `asyncapi.channel('mychannel').publish().message()._json.traits`
Operation trait: `asyncapi.channel('mychannel').publish()._json.traits`

Up for discussion:
If the traits are already applied, would you really want access to the original traits 🤔 ?

**Comment by derberg** [comment]
> If the traits are already applied, would you really want access to the original traits 🤔 ?

This was exactly my question after reading the context section. What is the use case here really?

**Comment by jonaslagoni** [comment]
You wouldn't IMO, however as stated you have no way to access those traits (without accessing the underlying json schema) if you for example parse an AsyncAPI document with the option `applyTraits = false`.

**Comment by derberg** [comment]
oh, you found the use case, if we allow `applyTraits = false` we should also enable easy access to traits

**Comment by magicmatatjahu** [comment]
@derberg @jonaslagoni We have option to access to traits by `x-parser-original-traits` extension[ here](https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L228), so we only must write API for that :)

**Comment by KhudaDad414** [comment]
@magicmatatjahu if someone wants to access traits with `{applyTraits: false}` then there won't be any `x-parser-original-traits` there.

**Comment by magicmatatjahu** [comment]
@KhudaDad414 Exactly, won't be, but will be the native `traits` object :) The `traits` object is only deleted with `{applyTraits: true}` ([code](https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L239)), so you should check first the `x-parser-original-traits` extension and then as a fallback check the `traits` field :) You can create PR, if you asked for it :)
