### ISSUE TITLE
Error: Document has to be either JSON or YAML.

### ISSUE THREAD

**Issue by jdall** [asyncapi/parser-js#23]
Apparently there is an error in my document, as the generator spews out:
```
Something went wrong:
Error: Document has to be either JSON or YAML.
    at parse (/usr/lib/node_modules/asyncapi-generator/node_modules/asyncapi-parser/lib/parser.js:75:11)
```
Please consider changing the message to something a bit more helpful. E.g. like the playground does it:
```
yaml: line 28: mapping values are not allowed in this context
```
Provided with this message, it was really easy to fix the issue.

Running ag v0.12.0

**Comment by fmvilas** [comment]
Agree. That's not helpful. Thanks!

**Comment by jdall** [comment]
If the following message could also be improved, it would be really nice:
```
Something went wrong:
Error: Invalid AsyncAPI document
    at parse (/usr/lib/node_modules/asyncapi-generator/node_modules/asyncapi-parser/lib/parser.js:93:11)
    at <anonymous>
```

**Comment by fmvilas** [comment]
@jdall both error messages have been improved in the latest version. I'm closing this issue but let me know if something goes wrong. Thanks!

**Comment by jdall** [comment]
Thanks. 
Great work - it's a lot more helpful now.

But something is a bit odd...
When generating html, I get the following error:
```
Something went wrong:
Template render error: (unknown path)
  Template render error: (/usr/lib/node_modules/asyncapi-generator/templates/html/.partials/content.html)
  Template render error: (/usr/lib/node_modules/asyncapi-generator/templates/html/.partials/operations.html) [Line 28, Column 23]
  TypeError: Cannot read property 'type' of null
```
I have yet to decide if something is missing in our A2S file... though generating markdown succeds.

But back to the oddity... the 'html/.partials/operations.html' file can't have an error at line 28, as it only has 15 lines...

I'm using ag v0.15.1

**Comment by fmvilas** [comment]
Yes, that's something I'm experiencing too and it's related to Nunjucks. Maybe you should open an issue on their repo? I'll try to guess what's happening in the meantime. Thanks!

**Comment by jdall** [comment]
It appears that this html generation error is no longer present when using ag v0.16.0
