### ISSUE TITLE
Handling schema true and false

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#232]
#### Describe the bug
You can define a schema as `true` or `false` to accept or reject all such as 
```
...
"properties":
   "age": true,
...
```

Now the problem is that our anonymous uid assignment tries to assign a uid to such schemas when its not possible.

This problem triggered the tests to fail for https://github.com/asyncapi/raml-dt-schema-parser/pull/25.
#### Expected behavior
There are a couple of ways we can handle this. 
1. We dont assign schemas which are `true` or `false` uids.
1. We convert `true` or `false` to its sugarcoated values `{}` and `{"not": {}}`

**Comment by jonaslagoni** [comment]
After a lengthy discussion on Slack with the json-schema community my perspective of the `true` and `false` schema's has changed. I saw it more as a `type` then the actual representation of absence and presence of types which is why it is defined as is.

**Comment by jonaslagoni** [comment]
@magicmatatjahu @derberg thoughts? 🤔

**Comment by derberg** [comment]
@jonaslagoni I saw your discussion in slack. If this doesn't represent the data but rather indicates if data can exist, then I guess we should not assign id to it. On the other hand, you would generate a data type for it right, even if it is just false/true?

**Comment by jonaslagoni** [comment]
> On the other hand, you would generate a data type for it right, even if it is just false/true?

Yes, with for example in typescript I would want to generate `any` type for that property. 

I think we shouldn't assign uid to those schemas and just ignore them as you said 😄

**Comment by magicmatatjahu** [comment]
I also ran into this problem 😅 However ids are not the biggest problem at the moment, but the fact that the Base model is not adapted to use the `true/false` schema (see [code](https://github.com/asyncapi/parser-js/blob/master/lib/models/base.js#L11) - we cannot assign to schema `false` value) and also that we [use draft-04](https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L92) in the parser and the [specification itself states](https://github.com/asyncapi/asyncapi-node/blob/master/schemas/2.0.0.json#L362) that it supports draft 07 - `true/false` schemas are supported from draft-07.

If you write `true/false` schemas you should have error like:

```txt
[
  "/components/schemas/lightMeasuredPayload/properties/lol should be object at line 156, column 9"
]
```

You can check it in https://playground.asyncapi.io/

**Comment by derberg** [comment]
but then just Base model needs to be fixed right? the problem that is there is not intentional imho. It is a typical check you do there, to throw an error if an argument is not passed to the function. We just need a better check, if json is undefined, or am I missing something?

**Comment by magicmatatjahu** [comment]
@derberg You're right, it's check not only for Schema but only for other models... so we should override constructor for Schema model like:

```js
class Schema extends Base {
  constructor (json) {
    const typeOf = typeof json;
    if (typeOf !== 'object' && typeOf !== 'boolean') throw new ParserError(`Invalid JSON to instantiate the ${this.constructor.name} object.`);
    this._json = json;
  }
  // rest of class
}
```
