### ISSUE TITLE
Missing schema test for description

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#233]
#### Describe the bug
We do not have any schema test for `description` which is part of JSON Schema draft 7.

#### Expected behavior

would expect something like the following test
```
  describe('description', function() {
    it('should return a string', function() {
      const doc = { description: 'some description' };
      const d = new Schema(doc);
      expect(d.description).to.be.equal(doc.description);
    });
  });

```

**Comment by fr3shw3b** [comment]
Hi, I'm happy to make a contribution for this. However, does this issue still exist?
I ask as I can see there is the description test mixin which is being pulled into the models/schema_test.js in the `#mixins` describe block.

https://github.com/asyncapi/parser-js/blob/master/test/mixins/description_test.js
https://github.com/asyncapi/parser-js/blob/master/test/models/schema_test.js#L545

**Comment by derberg** [comment]
@jonaslagoni @magicmatatjahu I agree with @fr3shw3b . Looks like this one can be closed and we do not need anything super explicit. We have pretty good coverage in schema model:
```
schema.js                      |   92.55 |    81.58 |     100 |     100 | 174,241-249,261-285
```
only a few tests missing for the some conditions

**Comment by magicmatatjahu** [comment]
Yep, we test some repetitive fields inside mixins.

**Comment by magicmatatjahu** [comment]
@fr3shw3b If you want you can write test for uncovered lines as @derberg mentioned

**Comment by fr3shw3b** [comment]
@magicmatatjahu Alright, I can do that, do we need a new issue to associate the PR with or can we stick with this one?

**Comment by magicmatatjahu** [comment]
@fr3shw3b Hi! We haven't, so if you wanna do that, please also create, as you mentioned, separate issue. We will be very grateful! :)

**Comment by derberg** [comment]
closing as this one requires no action
