### ISSUE TITLE
Wrong position information about errors in the root of the document

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#240]
#### Describe the bug
If I add some additional property to the root of the document (which is not allowed) I get an error like below (if I combine it from `title` and `startLine` and `startColumn`)

```
[
  "/ should NOT have additional properties on line undefined, column undefined"
]
```

#### How to Reproduce
Try to parse AsyncAPI document with property `test: true` on the root of the document.

#### Expected behavior
I should not only get information `/ should NOT have additional properties` but also an indication on where the error happened in the document so the user can easily find it

**Comment by KhudaDad414** [comment]
@derberg All we get from ajv is this:
```
{
  keyword: 'additionalProperties',
  dataPath: '',
  schemaPath: '#/additionalProperties',
  params: { additionalProperty: 'test' },
  message: 'should NOT have additional properties'
}
```
would that help if we add the additionalProperty to validationErrors?
we can go from this:

```
  {
    title: '/ should NOT have additional properties',
    location: { jsonPointer: '/' }
  }
```
to this:

```
  {
    additionalProperty: 'test',
    title: '/ should NOT have additional properties',
    location: { jsonPointer: '/' }
  }
```
then we can create a customized message like: `Please remove 'test' from /`.
does this solve the issue? am I missing something?

**Comment by derberg** [comment]
@KhudaDad414 hey, I think it is more about looking for a bug in `improveAjvErrors`

> `/ should NOT have additional properties on line undefined, column undefined`

The problem here is the `undefined` part. So info about `/ should NOT have additional properties` is not enough as you might have large document where you add something like `info2` somewhere in the document and you need to figure where it is located. The error message should tell you what line and column in the document is it. 

Now parser will give you correct info when you add something inside the asyncapi doc (check against the playground)
```
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
  test: {}
channels: {}
```

but when you add something to the root, it fails with undefined:
```
asyncapi: '2.0.0'
info:
  title: Streetlights API
  version: '1.0.0'
test: {}
channels: {}
```

I want to know where to look for this additional property, that it is line 5 column 1

does it make sense?

**Comment by KhudaDad414** [comment]
@derberg got it. created a pull request fixing the issue.
