### ISSUE TITLE
Measure performance of the parser

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#252]
#### Reason/Context
The parser should be fast and lightweight. We should always make sure about it on PR level:
- measure bundle size to not make browsers cry when fetching
- measure parsing performance
- always check those to make sure a given feature doesn't affect the performance of the parser

#### Description
Please try answering few of those questions
- have a github action that measures both
- discuss and set limits on when PR should be blocked
- publish performance tests results in readme
- get  from community a super large asyncapi document that we can use for testing

**Comment by magicmatatjahu** [comment]
We can use https://ajv.js.org/standalone.html to generate validate function for our schema to improve performance. At the moment we "compile" schema in each `parse` function execution ([line](https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L94)). I don't know how we can speed parsing, but I think that it should be faster :)

**Comment by derberg** [comment]
still needed
