### ISSUE TITLE
Split package to parser and parser-api packages

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/parser-js#267]
At the moment parser in source code has two main parts: validation/parsing and corresponding models which share the API for parsed schema: `AsyncAPIDocument`, `Schema`, `Operation` etc models.

My suggestion is split package to two separate ones:
- `@asyncapi/parser-api` or `@asyncapi/parser-models` - package only with models (and with API),
- `@asyncapi/parser` - package for validation and parsing which will use above package with API.

Why this is needed?
- you can parse schema in server-side and send parsed schema to front-end part and use API by `@asyncapi/parser-api` package - you don't need include dependencies for parser in both sides, in server and client side. For client side this is very important, the smaller the application the better - example: https://github.com/asyncapi/studio/pull/17 and https://github.com/asyncapi/html-template/pull/166
- if we go with another parser like for `go` language, we can reuse API from this parser like in above situation - parse by go schema and send to front-end app, so we can have few parsers but only one API for JS apps :) 
- we can significantly slim down our React component - now, after bundling, 90% of the code is a code related to parser and its dependencies. Of course in some situation user must use parser to use React component (when doesn't have a server for parsing), but we can allow passing parser instance as prop to React component and component will be independent to parser, not like currently.

As we can see I only have problems related to front-end apps, but maybe someone has another use cases. Feel free to comment!

Related issue: 
Stringify parsed schema - https://github.com/asyncapi/parser-js/issues/266

**Comment by magicmatatjahu** [comment]
We split the models domain so that webpack can treeshakable module, but an issue is still opened for the second variant - using the package for other parsers.

**Comment by magicmatatjahu** [comment]
We can also rewrite package to the ESM to be full treeshakable.

**Comment by derberg** [comment]
@magicmatatjahu is it still valid?

**Comment by derberg** [comment]
ping pong @magicmatatjahu 😄

**Comment by magicmatatjahu** [comment]
We introduced needed changes by splitting models and model-helpers to separate CJS modules to enable tree-shaking. I am closing it.
