### ISSUE TITLE
Cannot access externalDocs from the root object

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#287]
#### Describe the bug
It is possible to describe `externalDocs` with the spec, but there is no function to get it.
https://www.asyncapi.com/docs/specifications/2.0.0#A2SObject

#### Expected behavior
Expected a function to be able to retrieve such a property.

**Comment by magicmatatjahu** [comment]
@jonaslagoni We are using mixins to add to models repetitive intents -> https://github.com/asyncapi/parser-js/blob/master/lib/models/asyncapi.js#L270 :)

**Comment by jonaslagoni** [comment]
Ahh, right 🤦
