### ISSUE TITLE
Add description for used custom extensions in parser

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/parser-js#291]
Currently our parser adds an internal (started by `x-parser`) custom extensions to define missed/additional info about spec/some part of spec. Only extensions related to circular refs are described in main `Readme.md` of repo. We should make description for every custom extensions applied by parser to spec.

AC:
- find all custom extensions and add understandable description for them in `Readme.md`

Related to comment https://github.com/asyncapi/parser-js/pull/288#pullrequestreview-642974913

**Comment by vishesh13byte** [comment]
I tried to find all the custom extensions and found these custom extensions ,is this list complete?

- 'x-parser-spec-parsed'
- 'x-parser-message-name'
- 'x-parser-schema-id'
- 'x-parser-circular'
- 'x-parser-circular-props'

**Comment by derberg** [comment]
there is also `x-parser-message-parsed`, `x-parser-original-traits`, `x-parser-original-payload`, `x-parser-original-schema-format`.

**Comment by vishesh13byte** [comment]
I am understanding the usages and implementations of these extensions, will try to come up with concise descriptions for them.
💯

**Comment by vishesh13byte** [comment]
I have tried to add concise descriptions for all the custom extensions based on my understanding of their use cases and implementations. I have created pull request #295 ,please have a look . 🙏

Thank you.

**Comment by jonaslagoni** [comment]
Closing as it should be solved in https://github.com/asyncapi/parser-js/pull/295
