### ISSUE TITLE
Confused input argument for parser

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#308]
We currently define the input document as type [string](https://github.com/asyncapi/parser-js/blob/974be738947a1752142d77db5c737571163b7ad3/lib/parser.js#L34). 

However, both string and object are supported because the input parses through the underlying [toJs](https://github.com/asyncapi/parser-js/blob/974be738947a1752142d77db5c737571163b7ad3/lib/utils.js#L108) function.

What should be considered "correct"? Both "string" and "object" or just "string"? 🤔

**Comment by derberg** [comment]
looking at logic in `toJs` and especially [this](https://github.com/asyncapi/parser-js/blob/master/lib/utils.js#L115-L120) part, it should be both

**Comment by jonaslagoni** [comment]
Yea I agree

**Comment by vishesh13byte** [comment]
From what I understood, the parser works fine for both string and object type inputs but we only define input as string as mentioned above so what we have to do 😅? Do we just have to define that input can be either a string or an object like : `@param {(String | Object)} asyncapiYAMLorJSON` because it already supports object type too 🤔. Please guide me.

**Comment by jonaslagoni** [comment]
> Do we just have to define that input can be either a string or an object like : `@param {(String | Object)} asyncapiYAMLorJSON` because it already supports object type too

@vishesh13byte yes exactly, and add a test for the parser which takes an object input the same way that we have simple string inputs such as here - https://github.com/asyncapi/parser-js/blob/bc7980fb4596ee344834dd35b7ac958326514053/test/parse_test.js#L13

Let us know if you have more questions 🙂

**Comment by vishesh13byte** [comment]
I created another file  ''./good/asyncapi_object_type.yaml"  in the _good_ folder which consists of sample asyncapi document but now I am stuck as do I just need to write a simple test just as : 
` it('should parse YAML', async function() {
    const result = await parser.parse(inputYAMLObjectType, { path: __filename });
    expect(JSON.stringify(result.json())).to.equal(outputJSON);
  });`
where `inputYAMLObjectType = fs.readFileSync(path.resolve(__dirname, './good/asyncapi_object_type.yaml'), 'utf8');` **?**
Also, just to be clear I used the document used in asyncapi docs as I believe it is an object type document or maybe I am wrong. Please guide me,

**Comment by derberg** [comment]
I don't think you need to create another test file, just add a test case `should parse AsyncAPI document passed as JS object` and use existing test file. Make sure [this](https://github.com/asyncapi/parser-js/blob/974be738947a1752142d77db5c737571163b7ad3/lib/utils.js#L108-L113) condition is satisfied in your test. So the initial format of the input should be specified as `js` and not `yaml` for example. Read the file in the test and convert to object with `JSON.parse()` and pass this object to parser.

**Comment by vishesh13byte** [comment]
@derberg @jonaslagoni can you please have a look at pull request #312 ,please point it if I did something wrong.

Thank you.

**Comment by magicmatatjahu** [comment]
@vishesh13byte Hi! I added one comment, thanks for Pr! :)
