### ISSUE TITLE
Parse and validate bindings

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/parser-js#315]
#### Reason/Context

Part of https://github.com/asyncapi/spec/issues/507

Already we have defined JSON Schemas for official supported bindings in `bindings` repo by [this](https://github.com/asyncapi/bindings/pull/60) PR. We should think how to handle validation of bindings in the parser side.

Some my insights and founded problems:
- we shouldn't write models/mixins (generally functions for retrieving data) for bindings due to generic character of bindings. We can think about it in the future, but not now. It's not important now.
- for binding dev/user can define version of binding so we cannot make reference to appropriate version of binding inside the official JSON Schema of spec, however, we should figure out a way to find out which version the user has used and validate the binding according to that version in parsing time, and how to "download" corresponding JSON schema.
- Nice to have, but not needed in first implementation: figure how to avoid unnecessary downloading the schemas of bindings in each validation/parsing of given AsyncAPI spec. Download the schemas in release step of parser-js or maybe make something like memo system inside parser? I don't know which will be better. Very important here is our `react-component` and in the future other front-end apps/libs. In the front-end side parser should be fast as possible and small so we cannot bundle every binding schemas inside parser package. 

Part of https://github.com/asyncapi/spec/issues/507
It's related to https://github.com/asyncapi/parser-js/issues/50

**Comment by GeraldLoeffler** [comment]
A typical definition of `bindingVersion` in a bindings specification (say, for AMQP in https://github.com/asyncapi/bindings/tree/master/amqp#channel-binding-object) is: `The version of this binding. If omitted, "latest" MUST be assumed.`

So the parser must be able to 
* retrieve the JSON schema for a given `bindingVersion` of a given binding (say AMQP)
* or, if no `bindingVersion` is given in the AsyncAPI doc, or if `bindingVersion` is given as `latest`, determine what the latest available version of that binding is, and retrieve that,
* and then use that exact JSON schema for validation.

**Comment by derberg** [comment]
Bindings are part of the spec, so should be part of `https://www.npmjs.com/package/@asyncapi/specs`. I don't think there is much to do in the parser itself. We just need a proper workflow on `bindings` repo that whenever we have changes in JSON Schemas, we push an update to https://github.com/asyncapi/asyncapi-node. "Push an update" I mean push updated JSON Schema to `asyncapi-node`, and original AsyncAPI JSON Schema file will have `$ref` to given binding as local file, we can even resolve it when publishing `@asyncapi/specs` package. 

Why not much to do on the parser side? as once the linking between main schema and bindings are done, we get validation out of the box

**Comment by magicmatatjahu** [comment]
@derberg But if you bind `latest` version of binding inside the spec JSON Schema, how do you handle the other versions of bindings in validation?

**Comment by derberg** [comment]
we need to support all the versions, but still, better to do it in [JSON Schema](https://github.com/asyncapi/asyncapi-node/blob/master/schemas/2.0.0.json#L754) rather than the parser. Might be that to make things easier, we end up moving JSON Schemas of bindings to `asyncapi-node`, I'm not sure about that, did not dig the topic

**Comment by magicmatatjahu** [comment]
Still valid.
