### ISSUE TITLE
Add format object type for MessageExample

### ISSUE THREAD

**Issue by lbroudoux** [asyncapi/parser-js#321]
#### Reason/Context

As of (near future) `2.1.0` version of specification, message examples may contain clearly described properties like `payload`, `headers`, `name` and `summary`. Introducing new `MessageExample` into previous version of parser was a breaking change as early versions of library just deal with `any[]` for message examples. However I do think it's still a best practice and an adoption driver to have formally typed and described objects to manipulate specification concepts.

#### Description

I propose to introduce a new `MessageExample` type as it was done [here](https://github.com/lbroudoux/parser-js/commit/3f9f669c8357cc1e7979d540e34fe73b242107b9).

It will be a breaking change as the signatures of `examples()` function in Message will move from `any[]` to `MessageExample[]`. Also the `payload` property navigation will no longer be valid as we'll now have the `payload()` function returning the actual payload property or null if undefined.

**Comment by magicmatatjahu** [comment]
Issue is resolved in v2 ParserJS - now in https://github.com/asyncapi/parser-js/tree/next-major branch
