### ISSUE TITLE
feat: supporting 'x-parser-refed-from' extension.

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/parser-js#334]
#### Why we need this improvement?
   We need an extension to specify the components' origin if parsed by `@apidevtools/json-schema-ref-parser` from a `$ref` link.
#### How will this change help?
  If we want to optimize the `AsyncAPIDocument` that is parsed by the parser, we need a way to identify duplicate components in `AsyncAPIDocument`. currently, there is no way to distinguish between a component that is $refed and parsed by `@apidevtools/json-schema-ref-parser` and a component that is in the specification file itself.
#### What is the motivation? 
  Currently I am working on `@asyncapi/optimizer` and the library needs this piece of information to function correctly by this flow:
1) Parse the async API document using parser.
2) use the helper methods of `AsyncAPIDocument` and figureout which optimization is needed.
3) apply those optimizations.
3) convert the `AsyncAPIDocument` back to it's original form (JSON or YAML)

### Implementation
Before passing the AsyncApi specification file to `@apidevtools/json-schema-ref-parser` for defererencing, we can use this function to add the extension:

```
function addRefSource(mySchema) {
  for (const key of Object.keys(mySchema)) {
    if (typeof mySchema[String(key)] !== 'object') {
      if (key === '$ref') {
        mySchema[String('x-parser-refed-from')] = mySchema[String(key)];
      }
    } else {
      addRefSource(mySchema[String(key)]);
    }
  }
};
```
### Known issues with this approach
This approach will make some other extensions to misfunction. (After three hours of debugging, I couldn't figure out why.)
the issue is that `"x-parser-schema-id"` and `"x-parser-message-name"` will always assigned an anonymous id. like `"<anonymous-schema-2>"` 
(You can [compare](http://www.jsondiff.com/) the following objects if the explanation is not clear.)

#### [`AsyncAPIDocument` after the extention](https://gist.github.com/KhudaDad414/efda5e1756cebe994cc1317776c14a20)

**Comment by magicmatatjahu** [comment]
> This approach will make some other extensions to misfunction. (After three hours of debugging, I couldn't figure out why.)
the issue is that "x-parser-schema-id" and "x-parser-message-name" will always assigned an anonymous id. like "<anonymous-schema-2>"

Because by single `$ref` under the hood the `@apidevtools/json-schema-ref-parser` moves the reference from one JS object to another, so it's not a copy of object, but original. Due to this fact, some referenced schemas/messages ahve normal `x-parser-schema-id` etc names like `testSchema`. If you add before dereferencing the new field - in your case new extension - and end with:

```js
$ref: ...
'x-parser-refed-from': value from $ref
```

then `@apidevtools/json-schema-ref-parser` merge the object from `$ref` with your "new" object like in JS:

```js
const dereferenced = { ...ref, 'x-parser-refed-from': ... }
```

so it's not an reference to original `$ref` but copy of `$ref` with additional fields.

**Comment by derberg** [comment]
First of all 👏🏼 for great quality of this issue, well described with awesome examples, super clear for anyone!

Did you try the option provided by `dereference` function, that you can pass in a callback that gets access to dereferenced schema object? [link to docs](https://apitools.dev/json-schema-ref-parser/docs/ref-parser.html#dereferenceschema-options-callback)

**Comment by KhudaDad414** [comment]
> Because by single `$ref` under the hood the `@apidevtools/json-schema-ref-parser` moves the reference from one JS object to another, so it's not a copy of object, but ref to original. Due to this fact, some referenced schemas/messages have normal `x-parser-schema-id` etc names like `testSchema`. If you add before dereferencing the new field - in your case new extension - you end with:
> 
...and that is how I wasted three days of my life. I mean all I need to know if an object is a $ref of another is to compare them using === sign.

**Comment by magicmatatjahu** [comment]
@KhudaDad414

Together with Łukasz we have a saying: "What you have learned is yours" 😄 

> I mean all I need to know if an object is a $ref of another is to compare them using === sign, since @apidevtools/json-schema-ref-parser maintains object reference equality.

Yes, exactly, if two objects has this same reference, you have 99.99% percent of sure that you operate on some ref from `components/**`

This 0.01% is a case when you have object like

```js
{
  $ref: ...
   // other fields
}
```

so then `@apidevtools/json-schema-ref-parser` will merge the objects and create from them new reference.

**Comment by magicmatatjahu** [comment]
@KhudaDad414

Together with Łukasz we have a saying: "What you have learned is yours" 😄 

> I mean all I need to know if an object is a $ref of another is to compare them using === sign, since @apidevtools/json-schema-ref-parser maintains object reference equality.

Yes, exactly, if two objects has this same reference, you have 99.99% percent of sure that you operate on some ref from `components/**`

This 0.01% is a case when you have object like

```js
{
  $ref: ...
   // other fields
}
```

so then `@apidevtools/json-schema-ref-parser` will merge the objects and create from them new reference.

**Comment by KhudaDad414** [comment]
@magicmatatjahu thanks for the explanation. I really appreciate it. :)

**Comment by magicmatatjahu** [comment]
@KhudaDad414 No problem. Protip for future: If you will stuck on another problem longer than 1 day, easier will be ask on our slack, because someone could know solution for your problem :)

**Comment by magicmatatjahu** [comment]
Mea culpa... I see it now 🤦🏼  but ultimately, you @KhudaDad414 know the solution 😄

**Comment by KhudaDad414** [comment]
@derberg is right. I should have gone through the documentation, but still, two days of debugging is better than 2 minutes of reading the documentation.😆

**Comment by derberg** [comment]
@KhudaDad414 actually I quite often do the same as I don't trust developers docs and their up-to-date-ness 😆
