### ISSUE TITLE
operationId is missing

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-js#338]
#### Describe the bug
The operation object is missing the `operationId` method to retrieve the `operationId` attribute of AsyncAPI.

#### Expected behavior
I should be able to do stuff like `asyncapi.channel('mychannel').publish().operationId()`.

**Comment by hionnode** [comment]
Can I take this up ?

**Comment by magicmatatjahu** [comment]
`operationID` you can retrieve by `id()` function https://github.com/asyncapi/parser-js/blob/master/lib/models/operation-traitable.js#L27

**Comment by fmvilas** [comment]
LOL! What's even worst is that I wrote this code 🤦‍♂️ 

@hionnode thanks a lot for jumping into the issue. I'm gonna close this one as it's not really an issue but if you want to contribute to AsyncAPI I can help you find other issues. Let me know!
