### ISSUE TITLE
Parser should support recommended schema formats

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#339]
#### Describe the bug
Currently, the spec [recommends certain formats to be supported](https://www.asyncapi.com/docs/specifications/v2.1.0#messageObjectSchemaFormatTable), so how come we don't support them? 

It is especially weird considering we already have all the parsers, for them, as they are used in the generator: https://github.com/asyncapi/generator/blob/0df562081e79c51322125ead68d46a7d8d00bf67/lib/generator.js#L60

#### Expected behavior
I expected that by default the parser should understand schema formats for which the specification say is recommended to support.

**Comment by magicmatatjahu** [comment]
I don't think so that it should be supported in parser by default, because I see two problems:
- parser you can also use in browser, so the smaller the package the better. Avro and OpenAPI formats add about 100kb (minified) to the bundle, RAML about 3 mb, so as you can see then parser will weight about 4MB :) We had such an issue in the react-component due to this format -> https://github.com/asyncapi/asyncapi-react/issues/160
- people should have possibility to write and use their own parser for recommended formats

And as you mentioned, we have defined parsers for recommended formats as standalone plugins, so I think that our parser follows by recommendation in the spec :)

**Comment by derberg** [comment]
I also do think parser should only by default support default AsyncAPI schema format as it is now. Parser is a critical package that must be as lightweight as possible. We should just properly handle errors when parser is used against different formats (what we discussed in https://github.com/asyncapi/parser-js/pull/310)

For example raml data types parser in not even supporting browser. As @magicmatatjahu wrote, we need this modularity in place to enable users to use their own custom parsers if they want

**Comment by jonaslagoni** [comment]
Good point on the small-as-possible problem, did not dawn on me that is the use-case as well here. While it is a good perspective to have, I want to fire a few shots at it 😛 

By not including these packages by default we have some discrepancies between tooling, which affects the end user's experience with them. Especially tooling providers NEED to know about and maintain on their own extra schema parsers, which I don't think is fair, or a great experience for the tooling maintainer 😄 

> Oh, you could use your AsyncAPI document in the playground? Unfortunately, this other tool forgot about adding these extra, some would say "required", parsers to fully work and support your use-cases 🤷. 

Regarding the point about modularity, they most certainly should be able to, which is also support, even to overwrite existing schema parsers, meaning adding default ones does not affect their use-case - https://github.com/asyncapi/parser-js/blob/826b36922260254ba23d162cda309fc72f552c49/lib/parser.js#L221

I am all for keeping a minimal version of the parser if it really is necessary, but I would opt for a fully included parser as well 🙂

**Comment by derberg** [comment]
> Especially tooling providers NEED to know about and maintain on their own extra schema parsers, which I don't think is fair, or a great experience for the tooling maintainer

What do you mean? Then can maintain their own custom parsers only if the need them.

Shouldn't we just describe it properly in the readme really? The person that integrates should exactly know what and how to do that and I think we are missing this information in the readme

**Comment by jonaslagoni** [comment]
> What do you mean? Then can maintain their own custom parsers only if the need them.

Many end-users use other payload formats because that is what the spec allows, but on the tooling side, we suddenly require tooling vendors to manually enable this feature, and even know about it? That just sounds wrong to me 😅 

> Shouldn't we just describe it properly in the readme really? The person that integrates should exactly know what and how to do that and I think we are missing this information in the readme

A point I cannot wrap my head around is why would a maintainer by default NOT want their tool to be able to parse AsyncAPI files with different schema formats? 

Even if we are doing it to save `mb` for browsers, they too would want to support this no?

**Comment by magicmatatjahu** [comment]
> I am all for keeping a minimal version of the parser if it really is necessary, but I would opt for a fully included parser as well 🙂

But then react-component will weigh >4MB and nobody will want to use it 😅

**Comment by derberg** [comment]
> we suddenly require tooling vendors to manually enable this feature, and even know about it? That just sounds wrong to me

what do you mean by tooling vendors? tooling vendors most of time create their own tools :) but if they use AsyncAPI Parser they should use it according to documentation. I really don't see a problem here. By default parser supports formats that are MUST, and others are RECOMMENDED -> https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#schema-formats-table

> A point I cannot wrap my head around is why would a maintainer by default do NOT want their tool to be able to parse AsyncAPI files with different schema formats?

You do not only have tooling vendors in the community, you have also just users, that have their use cases. There are people that will only need default schema format. Who would use Avro if they do not use Kafka, as an example, so what is the point of adding this custom schema parser to their workflows? You have different consumers of AsyncAPI tools, people that build generic tools or just tools specifically designed for their use case.

> This "problem" was sprung from Stackoverflow with the reflection to Modelina, as Modelina does not support these different schema formats, as I completely forgot about it and first now realized 😅 As I see it, we do not have any tools that do not want to support these schema parsers?

well, what can I say, you should just enable custom parsers 🤷🏼 it is not a fault of the library that you didn't do that 😆 . Generator uses custom parsers, you should too.  Not sure if modelina is meant to support browser, then you should think on making custom parsers optional and allow others to register theirs, but not now, in generator you also have no way of registering your own custom parser yet.

Nevertheless, I still think Parser's readme lacks proper explanation and references.

**Comment by derberg** [comment]
> But then react-component will weigh >4MB and nobody will want to use it

@magicmatatjahu no because raml schema parser is anyway not browser compatible, so you won't enable it anyway

**Comment by derberg** [comment]
Of course if we really need we can always publish 2 packages, lightweight or all-inn. But would it solve your modelina issue? would you remember to read the readme and check the proper package name? (cannot find an emoji that shows doubt-full face 😄 )

**Comment by magicmatatjahu** [comment]
> Of course if we really need we can always publish 2 packages, lightweight or all-inn.

We can also create two instances of `Parser` with and without custom parsers, but then we should also rewrite the package from CJS to the ESM to enable full treeshakable -> ref https://github.com/asyncapi/parser-js/pull/285

**Comment by derberg** [comment]
@jonaslagoni how is it, did you change your view, or how does it look like? or will you just push update on readme?

**Comment by jonaslagoni** [comment]
🤷 it is just two different use-cases that contradict each other. Maybe the right approach is just to update the readme. I am trying not to take more tasks on, so if anyone wants to pick it up 👍

**Comment by derberg** [comment]
For others that would like to pick this issue. It is about specifying in the readme that Parser by default supports on AsyncAPI Schema Format and JSON Schema Format, and for others folks need to plugin additional plugins. I'm happy to jump on a call or something and explain more, but some details are already above

**Comment by Raksh7777** [comment]
Can I take this up?

**Comment by derberg** [comment]
@Raksh7777 definitely, lemme know if you need something
