### ISSUE TITLE
Setting `applyTraits` on Typescript projects

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/parser-js#354]
#### Describe the bug
I should be able to set `applyTraits` option in parser method without providing other options in Typescript projects. But since all the parameters are mandatory in `ParserOptions` type, the compiler will complain about specifying all of them.

#### How to Reproduce
Call the `parser` function with `{applyTraits: false}` option in a Typescript project.
you will get the following error: 
`Type '{ applyTraits: false; }' is missing the following properties from type 'ParserOptions': path, parse, resolve`

#### Expected behavior
The parser should parse the document without any errors.

**Comment by jonaslagoni** [comment]
Yes, this is a bug, all options should be optional 😅

**Comment by KhudaDad414** [comment]
so I am opening a PR for this.
