### ISSUE TITLE
parser doesn't validates the `$ref` links

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/parser-js#360]
#### Bug Description
If there is a typo in `$ref` value the parser should throw an error instead of passing the actual `$ref`.

#### How to Reproduce
```javascript
const parser = require('@asyncapi/parser');

parser.parse(`
asyncapi: 2.0.0
info:
  title: Streetlights API
  version: '1.0.0'
channels:
  smartylighting/event/lighting/measured:
    subscribe:
      message:
        $ref: "#components/messages/message1"
components:
  messages:
    message1:
      name: unusedMessage
      title: This is most definityly a message.
`).then((doc) => {
  console.log(doc.channel('smartylighting/event/lighting/measured').subscribe().message().json());
});
```
#### Actual Result
```javascript
{
  '$ref': '#components/messages/message1',
  schemaFormat: 'application/vnd.aai.asyncapi;version=2.0.0',
  'x-parser-message-parsed': true,
  'x-parser-message-name': '<anonymous-message-1>'
}
```
#### Expected Result
It should give an error message saying that my `$ref` path is broken or does not exist.

**Comment by jonaslagoni** [comment]
Since we don't want errors to be thrown but rather bundled together, to throw one big error in the end (I would assume so? git blame @derberg @fmvilas), this option is set to true: https://github.com/asyncapi/parser-js/blob/235efd5cb33df00c206bea3e9b09be9cd9587d87/lib/parser.js#L153

However, we never check that the dereference succedded, not sure if the dereference call actually returns any content, [docs say nothing](https://apitools.dev/json-schema-ref-parser/docs/ref-parser.html#dereferenceschema-options-callback).

**Comment by fmvilas** [comment]
Yeah, the idea is that it continues to throw one big error at the end. I'm now wondering if `continueOnError` actually does that 🤔

**Comment by derberg** [comment]
> I'm now wondering if continueOnError actually does that

it does, it gives an array of all errors

> continueOnError: true

it is just an option in refs parser library that we leverage. As you know, when I added custom validations, I did not follow this principle, as far as I remember, my bad. The same option to group errors is also used in Ajv.

hard to say why there is no error, would require some debugging

**Comment by smoya** [comment]
Can we solve this with a `pattern` field on the JSON Schema `Reference Object` ?

**Comment by derberg** [comment]
dunno, maybe there is already some super bullet-proof regex created by the community that can validate `$ref` as it can represent, link to file, URL or location inside the existing document. It definitely exceeds my knowledge of regex 😄

**Comment by smoya** [comment]
Otherwise, AJV should throw an error (`MissingRefError`) anyway. See this example I built: https://onecompiler.com/nodejs/3y9pgk7py

**Comment by smoya** [comment]
Issue is resolved in v2 ParserJS - now in https://github.com/asyncapi/parser-js/tree/next-major branch thanks to Spectral. Pending to add a test. 

cc @magicmatatjahu

**Comment by magicmatatjahu** [comment]
Resolved by https://github.com/asyncapi/parser-js/pull/676
