### ISSUE TITLE
docs website for the api of the parser

### ISSUE THREAD

**Issue by boyney123** [asyncapi/parser-js#387]
#### Reason/Context

At the moment the API is sat in the Readme file https://github.com/asyncapi/parser-js/blob/master/API.md, which is fine and seems to work, but I wonder if we could bring our API alive?

Maybe it's just me, but when I interact with 3rd party libs, I find it very useful to have the website render the APIs with examples too for each function.

Here are some open-source examples of what I mean:

- https://date-fns.org/v2.25.0/docs/isDate
- https://jestjs.io/docs/puppeteer
- https://webdriver.io/docs/api/browser/deleteCookies

As you can see the general theme with these is:

- The API is listed down the side
- Clear docs + examples for each function which is nice

Most of them use https://docusaurus.io/showcase which we might be able to use too, or maybe somehow add it to the AsyncAPI website, not sure.

### Why do we need this improvement?

Make the API more accessible with examples and docs to go with the APIs, just be easier to get up and running, and search for things. 

---

Wondered what you all think?

**Comment by boyney123** [comment]
Very cool @derberg , thanks for sharing will look at the workflows

**Comment by boyney123** [comment]
Yeah I think the left nav idea should good and lists the functions etc from the README file, I have no idea how we can add examples to the functions. 

As a dev I would love to see the function and maybe exampels with each API.... maybe this can be done in the API.md file no idea....

Seems like we have some standard urls atm:

- https://www.asyncapi.com/tools/parsers
- https://www.asyncapi.com/tools/modelina
- https://www.asyncapi.com/tools/github-actions

Which I assume is `https://www.asyncapi.com/tools/{tool}` so maybe something like `https://www.asyncapi.com/tools/{tool}/docs` would be good?

Example `https://www.asyncapi.com/tools/parsers/docs` would render the docs for each tool.

>but I guess API.md is not the only one, right? would be nice to have stuff that are already in the readme, might be that we need to pull these out to separate markdown files to handle them the same was as API.md?

Sorry, not sure if I understand what you mean here

**Comment by alequetzalli** [comment]
> the question is where does it go? `https://www.asyncapi.com/docs/tools/parser-js/` ? and `https://www.asyncapi.com/docs/tools/` should list all the others? and left nav should be the same as we have here https://www.asyncapi.com/docs/getting-started ?
> 
> @alequetzalli this is definitely a topic for ya where your voice is super important 😄 yet another one 😄

Yes! According to our content buckets from the [Diátaxis Framework](https://diataxis.fr/) that we're using to re-structure our IA of the Docs, all of these API docs go under **Reference**. These API docs and others should be moved under our Docs site, and we need to select an API tool to generate nice API docs. I don't know why we can't just use swagger or something similar, then tailor the CSS to our brand needs?   

**The look of API reference docs in our site is something we'll need to bring Missy Turco in**, does she have a GH handle we can tag her into these convos in? 🤔 

I want us to start thinking about moving toward nicer and cleaner URLs, such as:
- `https://docs.asyncapi.com/concepts/traits` 
- `https://docs.asyncapi.com/tutorials/streetlights` 
- `https://docs.asyncapi.com/reference/parser-js` 
- `https://docs.asyncapi.com/reference/modelina` 

(yes, this means 301 re-direct setups, already a convo I've told Lukasz I want to tackle in my 1st year here as part of the needed IA changes) 

The `/tools` section will not live where it currently resides, it needs to be moved to another appropriate content bucket. SDK docs for Modelina should go under broader content bucket **Reference**.

**Comment by magicmatatjahu** [comment]
Still valid.
