### ISSUE TITLE
allSchemas does not return "all" schemas as expected 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#39]
**Reason**

Given the definition of the function, one would expect ALL the schemas to be returned, however this is not the case. As seen in the [implementation](https://github.com/asyncapi/parser-js/blob/5b3d841921d049ad891a976741413db012146c81/lib/models/asyncapi.js#L171) it only shallowly look at schemas from messages and components.

**Description**

- Think about how it can be done recursive and handle circle references.
- Remember to update tests so they reflect this new behavior.

Hints:
- Discussed in https://github.com/asyncapi/parser-js/issues/32

**Comment by GreenRover** [comment]
+1

**Comment by hesyar** [comment]
+1

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/parser-js/pull/41
