### ISSUE TITLE
channel.servers() should return a list of all the servers by default

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-js#394]
#### Describe the bug
By default, `channel.servers()` returns an empty array. When a `servers` property is not present in a channel definition, the meaning is that this channel is present in all servers described in the `servers` section of the document.

#### Expected behavior
[This line](https://github.com/asyncapi/parser-js/blob/master/lib/models/channel.js#L56) should return an array with all the server names in the document.

**Comment by jonaslagoni** [comment]
Well, there are two views on this. 

As it currently stand with the parser, all it does (and nothing else) is give you the exact information that is available for that property. This is why it only gives you the information about whether someone defined a server reference in the channel or not. This is also why contentType does not return defaultContentType from the root object - https://github.com/asyncapi/parser-js/blob/08f425cb034c1a1d29f33399fcf78e16924cb28f/lib/models/message-traitable.js#L61

If we go with the other approach, and being knowledable about other properties, and try to interpret what your intent is, you won't be able to only get the channel servers. i.e. where you have a use-case that requires you to not lookup the root servers as well. 

Might need two functions for this? 🤔

**Comment by fmvilas** [comment]
I don't think it's the same. `channel.servers()` doesn't give you exactly what is on the AsyncAPI document. If you don't specify any `servers` property` at channel level, it gives you an empty array instead of `undefined`. So there you are already interpreting the intent. I just think the interpretation is incorrect.

On the other hand, `contentType()` returns **exactly** what's found in the AsyncAPI document. That's different.

**Comment by derberg** [comment]
Logically your point makes a lot of sense. You want parser to give you servers that channel is available at. 

But, are there other parts of the parser that work this way. Thing is that the way you work with the parser atm, I would be confused to see all the servers in returned array. I would first check if channel hasServers and in case of false read all servers from servers root.

**Comment by fmvilas** [comment]
Cool, time for a rewrite of the parser it seems 😄 Good to take this into account for the intent-driven one.

**Comment by smoya** [comment]
> Cool, time for a rewrite of the parser it seems 😄 Good to take this into account for the intent-driven one.

I was about to say this. From an intent point of view, I think it as "Just give me the servers where the channel is present". 
Btw, I just noticed we did not update the intent-driven [parser-api](https://github.com/asyncapi/parser-api/blob/master/docs/v1.md#operation) with latest changes on the spec. Servers are returned through Operations but not through Channels. Worth to add it I think.

**Comment by smoya** [comment]
@fmvilas this is already happening in the new development of the Parser-JS planned for 3.0.0 https://github.com/asyncapi/parser-js/blob/next-major/src/models/v2/channel.ts#L41-L50

Do you think it makes sense to close this issue and considered done? Or rather wait until we release it?

cc @magicmatatjahu

**Comment by fmvilas** [comment]
Cool! I'd just leave this open until the new version is released. It can still change so it's not yet done.

**Comment by magicmatatjahu** [comment]
Issue is resolved in v2 ParserJS - now in https://github.com/asyncapi/parser-js/tree/next-major branch
