### ISSUE TITLE
Dereference behavior does not follow AsyncAPI reference object and JSON Schema draft 7 behavior

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#404]
#### Describe the bug
We use the  [@apidevtools/json-schema-ref-parser](https://github.com/asyncapi/parser-js/blob/f17424a0639a61fb19d2004d96ca652b9ec09f5d/package.json#L68) dependency to resolve all references, however, this has a faulty implementation.

[AsyncAPI 2.2.0 defines a reference](https://www.asyncapi.com/docs/specifications/v2.2.0#referenceObject) as:
> The Reference Object is defined by JSON Reference and follows the same structure, behavior and rules. ... . This object cannot be extended with additional properties and any properties added SHALL be ignored.

[JSON Schema draft 7 defines the reference behavior](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-8.3) as:
> An object schema with a "$ref" property MUST be interpreted as a "$ref" reference. ... . All other properties in a "$ref" object MUST be ignored.

Meaning the two overlap in their behavior (lucky for us).

This means that given the following AsyncAPI document:
```yaml
asyncapi: '2.2.0'
info:
  title: Test overriding dereferenced objects 
  version: '1.0.0'
channels:
  test:
    publish:
      message:
        $ref: '#/components/messages/myMessage'
        name: 'MyOtherMessageName' # Should not be valid
components:
  messages:
    myMessage:
      name: 'MyMessage'
      payload:
        type: object
        properties:
          sentAt:
            $ref: "#/components/schemas/sentAt"
            description: 'test' # Should not be valid
  schemas:
    sentAt:
      type: string
      format: date-time
      description: Date and time when the message was sent.
```

Check out the [studio example](https://studio.asyncapi.com/?base64=YXN5bmNhcGk6ICcyLjIuMCcKaW5mbzoKICB0aXRsZTogVGVzdCBvdmVycmlkaW5nIGRlcmVmZXJlbmNlZCBvYmplY3RzIAogIHZlcnNpb246ICcxLjAuMCcKY2hhbm5lbHM6CiAgdGVzdDoKICAgIHB1Ymxpc2g6CiAgICAgIG1lc3NhZ2U6CiAgICAgICAgJHJlZjogJyMvY29tcG9uZW50cy9tZXNzYWdlcy9teU1lc3NhZ2UnCiAgICAgICAgbmFtZTogJ015T3RoZXJNZXNzYWdlTmFtZScgIyBTaG91bGQgbm90IGJlIHZhbGlkCmNvbXBvbmVudHM6CiAgbWVzc2FnZXM6CiAgICBteU1lc3NhZ2U6CiAgICAgIG5hbWU6ICdNeU1lc3NhZ2UnCiAgICAgIHBheWxvYWQ6CiAgICAgICAgdHlwZTogb2JqZWN0CiAgICAgICAgcHJvcGVydGllczoKICAgICAgICAgIHNlbnRBdDoKICAgICAgICAgICAgJHJlZjogIiMvY29tcG9uZW50cy9zY2hlbWFzL3NlbnRBdCIKICAgICAgICAgICAgZGVzY3JpcHRpb246ICd0ZXN0JyAjIFNob3VsZCBub3QgYmUgdmFsaWQKICBzY2hlbWFzOgogICAgc2VudEF0OgogICAgICB0eXBlOiBzdHJpbmcKICAgICAgZm9ybWF0OiBkYXRlLXRpbWUKICAgICAgZGVzY3JpcHRpb246IERhdGUgYW5kIHRpbWUgd2hlbiB0aGUgbWVzc2FnZSB3YXMgc2VudC4=) (it uses this parser library for bundling the references)

As it can be seen both `name` in the AsyncAPI reference object for the message is applied, which results in the message being called `MyOtherMessageName` and not `MyMessage`. 

Same with the JSON Schema the description of the payload message object it has the description `test` and not `Date and time when the message was sent.`

**Comment by smoya** [comment]
For the record, there is a recent effort on building JSON Schema foundational tooling with kind of (TBD) official support, lead by @jviotti and @Relequestual here json-schema-org/community#113.

**Comment by jonaslagoni** [comment]
Potential replacement for the dereferencing library: https://github.com/APIDevTools/json-schema-reader

**Comment by jviotti** [comment]
For the record, the `bundle` command of the JSON Schema CLI tool I've been working on properly does these kind of stuff: https://github.com/Intelligence-AI/jsonschema/blob/main/docs/bundle.markdown
