### ISSUE TITLE
Add support for messageId 

### ISSUE THREAD

**Issue by smoya** [asyncapi/parser-js#414]
#### Reason/Context
This is a follow-up issue coming from https://github.com/asyncapi/spec/issues/458.

#### Description
As per the RFC, we need to add support for `messageId` at message level. This issue helps tracking progress on it.
Note that it should not break any behavior in place, and the parser should be smart enough for detecting if you are using the new `messageId` field or rather relying on the name (no breaking change should be introduced, so it should be compatible with previous spec version)

Note: since the feature is not considered a breaking change, we could include it either on `2.3.0` or `3.0.0`, depending on how "fast" we move on.

cc @WaleedAshraf

**Comment by smoya** [comment]
@magicmatatjahu would you mind removing the `stale` label? Thks!

**Comment by magicmatatjahu** [comment]
Supported by https://github.com/asyncapi/parser-js/pull/510
