### ISSUE TITLE
Schemas are not assigned correct uid's

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#42]
Nested schemas without manually specifying the `$id` attribute never get assigned correct id's.

**Example**
```json
{
	"channels": {
		"test": {
			"parameters": {
				"testParam1": {
					"schema": {
						"type": "object",
						"properties": {
							"testParamNestedSchemaProp": {
								"type": "object",
								"properties": {
									"testParamNestedNestedSchemaProp2": {
										"type": "string"
									}
								}
							}
						}
					}
				}
			},
                        ...
		}
	}
}

```
given the above JSON I would expect the `$uid` of the schema to be `<anonymous-schema-1>`, `testParamNestedSchemaProp`, `testParamNestedNestedSchemaProp2`, however it is `<anonymous-schema-1>`, `undefined`, `undefined`.

One question, should the parameter schema not get assigned the uid `testParam1`?

**Comment by jonaslagoni** [comment]
Need some help defining the scope of this issue and answer the question of parameters @derberg @fmvilas :smile:

**Comment by derberg** [comment]
I'm too dumb to help out here without better understanding the subject, sorry. Logically I would also expect `testParam1`. Do you have some more data I could quickly use to play with?

**Comment by jonaslagoni** [comment]
Any help would be great 💯 We have a few tests which include anonymous schemas the [`allSchemas` test](https://github.com/asyncapi/parser-js/blob/5b3d841921d049ad891a976741413db012146c81/test/models/asyncapi_test.js#L182) and  most of the tests in [`parser_test.js`](https://github.com/asyncapi/parser-js/blob/master/test/parse_test.js) checks for anonymous schemas, might be a good place to fiddle around. Might need to include some extra tests 🤔

**Comment by jonaslagoni** [comment]
So this issue is actually a two part issue, however I think we can keep it all in one issue or?

#### First issue 
An issue lies with the assignment of anonymous schemas which are not done recursively.

#### Second issue
An issue lies with the assignment of proper ids of parameters and properties for objects which is what is described above.

**Comment by derberg** [comment]
@jonaslagoni ok, I think I now understand it more. But have a look on this test https://github.com/asyncapi/parser-js/blob/5b3d841921d049ad891a976741413db012146c81/test/models/asyncapi_test.js#L189-L194 you pointed me to

how would you like to improve the parser, what would you expect instead of the anonymous ids from the test example?
```
{
  channels: {
    test: {
      parameters: {
        testParam1: {
          schema: {
            $id: 'testParamSchema',
            test: true,
            k: 0
          }
        }
      },
      publish: {
        message: {
          headers: {
            test: true,
            k: 1
          },
          payload: {
            test: true,
            k: 2
          }
        }
      }
    },
    test2: {
      subscribe: {
        message: {
          payload: {
            $id: 'testPayload',
            test: true,
            k: 2
          }
        }
      }
    }
  },
  components: {
    schemas: {
      testSchema: {
        test: true,
        k: 3
      }
    }
  }
}
```

instead of `<anonymous-schema-1>` you want to have something like `anonymous-channel-test-publish-message-header` ? or?

regarding the recursive assignment of the IDs for nested objects. It is hard for me to have an opinion here, why would you need it as separate objects returned by `allSchemas`? you have a use case for it?

**Comment by jonaslagoni** [comment]
I would not change the naming of the `<anonymous-schema-1>` however when you have any nested JSON Schemas they are never assigned `<anonymous-schema-x>` ids. Which is needed when we want to return [`allSchemas`](https://github.com/asyncapi/parser-js/issues/39).

The use-case for returning all schemas is described in https://github.com/asyncapi/generator/issues/239 😄

**Comment by derberg** [comment]
got it

> One question, should the parameter schema not get assigned the uid testParam1?

after reading this one I thought you also would like to have some smart mechanism for providing more specific names for schemas instead of simple anonymous

>given the above JSON I would expect the $uid of the schema to be <anonymous-schema-1>, testParamNestedSchemaProp, testParamNestedNestedSchemaProp2, however it is <anonymous-schema-1>, undefined, undefined.

why `testParamNestedSchemaProp` and not anonymous as well? I hope it is not a stupid question :)

**Comment by jonaslagoni** [comment]
No questions are dumb 😄 It is the same principle as for parameters (IMO) that the schema uid should return the object property names and not an anonymous name, since we did actually provide a name for that schema. However one could argue that the property names are just a name that has nothing to do with the schema itself, hmm 🤔 What would you expect?

**Comment by derberg** [comment]
@jonaslagoni this is my point. I'm always supporting the minimum need, no exceptions and custom handling that just complicates the implementation. This is why the simplest approach is, `no $id? then you get schema under `anonymous*` key, with no ifs`. But I'm purely theoretical here as I'm not the user of this functionality

**Comment by jonaslagoni** [comment]
After some thinking I agree with you @derberg the property name should not reflect the id of the object, but just get assigned anonymous id. I'll change it in the PR 😄
