### ISSUE TITLE
Maybe make `stringify` function available on the instance of AsyncAPIDocument class

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#421]
The `stringify` function is at the moment static and available only directly on AsyncAPIDocument. We have the same with `parse` function from the same class.

from DX point of view, as a dev using the parser, it is confusing that:
- `stringify` can't be just used like other methods, `asyncapi.stringify()`
- `parse` is not actually a function outside the class, standalone like `parseFromUrl`

In templates accessing these with `asyncapi.constructor.stringify(asyncapi)` feels weird 🤔 

or is it just me?

**Comment by derberg** [comment]
@magicmatatjahu I totally forgot where is this coming from. I think I talked to you about it when I wanted to use `stringify` in java template....but they we ended up agreeing that it actually makes sense how it is done now.....do you remember?

We have https://github.com/asyncapi/parser-js#stringify so I guess topic completed?

**Comment by magicmatatjahu** [comment]
@derberg Yeah, the main point was that this function is not provided from the library and you have to use it as a static method of the class. In parser 2.0.0 it will be a normal imported function like:

```js
import { stringify, unstringify } from '@asyncapi/parser';
```

**Comment by derberg** [comment]
ok, then we can close as for current version usage is explained and documented
