### ISSUE TITLE
Support `security` field at Operation level

### ISSUE THREAD

**Issue by smoya** [asyncapi/parser-js#434]
#### Reason/Context
Part of https://github.com/asyncapi/spec/pull/584.

#### Description
Support `security` field containing an array of SecurityRequirement at Operation level.

As this is a good candidate to be in `v2.3.0` release, the PR should be created from and targeting `2022-01-release` branch.

As far as I see, the change we need to do is to add a new function called `security` into the `operation` model. I think we can copy the one from the `server` found in https://github.com/asyncapi/parser-js/blob/2022-01-release/lib/models/server.js#L65-L72

**Comment by sekharbans-ebay** [comment]
> #### Reason/Context
> Part of [asyncapi/spec#584](https://github.com/asyncapi/spec/pull/584).
> 
> #### Description
> Support `security` field containing an array of SecurityRequirement at Operation level.
> 
> As this is a good candidate to be in `v2.3.0` release, the PR should be created from and targeting `2022-01-release` branch.
> 
> As far as I see, the change we need to do is to add a new function called `security` into the `operation` model. I think we can copy the one from the `server` found in https://github.com/asyncapi/parser-js/blob/2022-01-release/lib/models/server.js#L65-L72

Ack. Is simply copying the function ok? Would you in addition like ServerSecurityRequirement (server-security-requirement.js) renamed to 'SecurityRequirement' and reused for both server and operation - or a OperationSecurityRequirement equivalent created?

**Comment by magicmatatjahu** [comment]
@sekharbans-ebay Hi!

> Ack. Is simply copying the function ok? Would you in addition like ServerSecurityRequirement (server-security-requirement.js) renamed to 'SecurityRequirement' and reused for both server and operation - or a OperationSecurityRequirement equivalent created?

as I see `server-security-requirement.js` is empty class, so you can create equivalent the `OperationSecurityRequirement` class. If in the future something additional will appear in the `ServerSecurityRequirement` class, we will create a separate class that will be extended both in `ServerSecurityRequirement` and in `OperationSecurityRequirement` classes, don't worry :)

**Comment by sekharbans-ebay** [comment]
Thanks so much Lokesh!
Hi @smoya, @magicmatatjahu, @derberg  - request review  please

**Comment by magicmatatjahu** [comment]
Handled by https://github.com/asyncapi/parser-js/pull/505
