### ISSUE TITLE
Export error type strings for other tools to use in error handling (e.g. invalid-json)

### ISSUE THREAD

**Issue by BOLT04** [asyncapi/parser-js#448]
#### Reason/Context
- This improvement is necessary so that the `parser-js` becomes the sole owner of these error types, and these strings aren't spread across multiple repos. When tools need these strings they can just **import the constants** exported by the parser.
- By having these errors exposed as an array or TypeScript type, other tools can leverage them in their validation and error handling
- This feature would be used in `server-api` at least. The request was motivated by this comment: https://github.com/asyncapi/server-api/pull/22#discussion_r780324931

#### Description
- What changes have to be introduced? R: a new JS module exporting these error type strings
- Will this be a breaking change? R: I don't think so, it should be a new **feature added as a minor release**. Other tools can import these constants or not.
- How could it be implemented/designed? R: Inside the folder `lib/errors` we could have a JS module that exports different objects. One for "client side" errors (input parameters), and another for the rest. Then add the strings that are documented in [here](https://github.com/asyncapi/parser-js#error-types) to the appropriate object.

**Comment by magicmatatjahu** [comment]
It should be resolved in the `2.0.0` of parserJS.

**Comment by BOLT04** [comment]
still relevant 🙂
