### ISSUE TITLE
Precompile AJV templates to allow CSP in browser to function

### ISSUE THREAD

**Issue by nictownsend** [asyncapi/parser-js#460]
https://ajv.js.org/standalone.html

> Ajv supports generating standalone validation functions from JSON Schemas at compile/build time. These functions can then be used during runtime to do validation without initialising Ajv. It is useful for several reasons:

> to avoid dynamic code evaluation with Function constructor (used for schema compilation) - when it is prohibited by the browser page Content Security Policy.

https://ajv.js.org/standalone.html#using-the-defaults-es6-and-cjs-exports

I'll take a look at implementing this via a PR but if I have no luck I may need other developers to help out.

**Comment by magicmatatjahu** [comment]
In Parser version 2.x this will be problematic due to the fact that we have moved to Spectral when it comes to validation - not only spec but custom validations as well - so I don't think so that it's still relevant. cc @derberg @nictownsend
