### ISSUE TITLE
Make parser auto-discover schema parsers mime-types

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-js#47]
While I was working on extracting RAML and OpenAPI schema parsers (#44), I realized that it's a bit painful to remember all the mime types that a given schema parser supports. It would be great to make the parser auto-discover these mime types.

For instance, instead of writing this:

```js
parser.registerSchemaParser([
  'application/vnd.oai.openapi;version=3.0.0',
  'application/vnd.oai.openapi+json;version=3.0.0',
  'application/vnd.oai.openapi+yaml;version=3.0.0',
], openapiSchemaParser);
```

You write this:

```js
parser.registerSchemaParser(openapiSchemaParser);
```

This will improve a few things:
1. You will no longer have to remember the list of mime types.
1. It will help with evolution. E.g., if a parser supports a new mime type, you'll only have to update to the latest version.
1. It's less error-prone.

## How?

By enforcing a common interface on schema parsers, e.g.:

```js
openapiSchemaParser.parse = function ({ message, defaultSchemaFormat }) { ... }
openapiSchemaParser.getMimeTypes = function () { ... }
```

**Comment by derberg** [comment]
My first step was to do a research to find a single source of truth for all the mime types out there and I even found https://www.npmjs.com/package/mime-db that lists mime types from locations like https://www.iana.org/assignments/media-types/media-types.xhtml 😄 

But now I get what you mean, that basically schema parser maintainer must always implement a function that will provide those mime types and that is it, they are still hardcoded in the library itself 🤦 

Anyway, on it 😄
