### ISSUE TITLE
ramldt2jsonschema package has link to fs module

### ISSUE THREAD

**Issue by zerobig** [asyncapi/parser-js#48]
The 'ramldt2jsonschema' module you are using has a link to the 'fs' module in the code. As a result, it turned out to be impossible to use parser version 0.14 with the asyncapi-react project when it is built only for the browser.

Is there anything you can do about this?

**Comment by derberg** [comment]
@zerobig Thanks for pointing it out. Sorry about that, luckily we figured that out and already work on a fix. It will be released soon, if not today than probably tomorrow -> https://github.com/asyncapi/parser-js/pull/44. I will setup a ref in the PR so once it is merged this issue will be closed and you will learn about it.

Btw, good to meet `asyncapi-react` user!
