### ISSUE TITLE
Update README with new logo banner

### ISSUE THREAD

**Issue by mcturco** [asyncapi/parser-js#490]
#### Reason/Context
This is to replace the old AsyncAPI logo in this repo's README with the banner attached below that represents the new branding.

**Here are a few guidelines for this change as well:**
1. Make sure you are using [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) only
2. Be sure to remove the old logo as well as the old title of the repo as this image will replace both elements
3. Make sure you link this image to the website: `https://www.asyncapi.com`
4. If there is any description text below the repo title, let's make it left-aligned if it isn't already, so as to match the left-alignment of the content in the new banner image

[Click here to download the image](https://github.com/asyncapi/parser-js/files/8232461/github-repobanner-parserjs.png.zip)

------

#### Banner preview
_Please note that this is only a preview of the image, the contributor should download and use the above zip file_ 

<img width="830" alt="Github_RepoBanner_Parser" src="https://user-images.githubusercontent.com/60163079/157881688-ef3879e0-9a25-466b-bd05-1033c6836386.png">

**Comment by harshi1122** [comment]
Hello @mcturco 
I am new to Open Source
Could you please assign me this issue?
I would love to work on it!

**Comment by heysolomon** [comment]
I am going to be working on this
