### ISSUE TITLE
parser library for java

### ISSUE THREAD

**Issue by jason53** [asyncapi/parser-js#503]
We have defined our REST APIs using the OpenAPI spec.  Additionally we have built some tooling around the OpenAPI spec files using the Java based swagger-parser (https://github.com/swagger-api/swagger-parser) library.  As we begin to create an Eventing Architecture we would like to use the AsyncAPI spec in addition to extending our tooling as well but unfortunately I have not found a Java based AsyncAPI parsing library.  Is there an existing Java based AsyncAPI parser library that I haven't found?  If not, are there any plans to create one?

**Comment by derberg** [comment]
@jason53 hey, sorry for commenting that late (luckily stale bot pulled it up).

I do not know anyone who would work on Java parser. If you want to work on it, please discuss it here -> https://github.com/asyncapi/community/discussions/categories/ideas. I will close this issue.

We welcome any contribution and would also welcome anyone who would like to maintain an official Java template. We can definitely help by sharing experience from writing Java Script Parser and serve as consultants, at least me 😄 

The only Java "parser" I know is https://github.com/aml-org/amf but have no idea really how it is adopted as it is maintained outside AsyncAPI org
