### ISSUE TITLE
parseFromUrl does not resolve relative references

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#504]
#### Describe the bug
Given the use of `parseFromUrl` I would expect that if the remote document contained relative references, they would be resolved based on the URL passed to `parseFromUrl` 🤔 

#### How to Reproduce

Given a reference such as `"$ref": "./components/parameters.json#/server_id"` in an AsyncAPI document located at `https://raw.githubusercontent.com/org/repo/main/asyncapi.json` I would expect it to fetch the parameter from `https://raw.githubusercontent.com/org/repo/main/components/parameters.json#/server_id` instead of trying to fetch it locally on the machine.

**Comment by derberg** [comment]
@jonaslagoni just to be sure, this is `feature` request, not really a `bug`. Especially that if someone wants to do that what you just described has an option to pass custom resolver to `parseFromUrl`. We just do not provide such a resolver out of the box
