### ISSUE TITLE
bumping ajv v8.5.0+ and draft-04 support

### ISSUE THREAD

**Issue by Dzixxx** [asyncapi/parser-js#506]
#### Describe the bug
I'm using AsyncAPI parser in my NestJS microservices (long story short -> OpenAPI decorators -> custom application scanner => dynamically generated AsyncAPI document <3). Since few days I have problem with draft-04 support (`keyword "id", use "$id" for schema ID...`) and base on AJV [documentation](https://github.com/ajv-validator/ajv#ajv-json-schema-validator) draft-04 support requires higher version than `^6.10.1` (actual version from package.json)

#### How to Reproduce
Upgrade `ajv` to higher version I guess 🤔 

#### Expected behavior
I'd like to know if this can be handled/upgraded otherwise I will have to probably switch to OpenAPI with some `x-...` properties cause it's blocking other packages to be upgraded 🤷 I'd like to help in any way but not sure how 😉

**Comment by WaleedAshraf** [comment]
Facing the same issue.

**Comment by derberg** [comment]
@Dzixxx @WaleedAshraf folks can you try with this https://github.com/asyncapi/parser-js/pull/423 how will it affect your use cases

**Comment by GreenRover** [comment]
+1

**Comment by magicmatatjahu** [comment]
Parser 2.x uses ajv in the `8.11.0` version. I will close this one when we will release major version (not rcs).
