### ISSUE TITLE
Better x-parser-schema-id

### ISSUE THREAD

**Issue by GreenRover** [asyncapi/parser-js#516]
#### Reason/Context
If there is not proper "x-parser-schema-id", meaning those "anonym..",
[Modelina ](https://github.com/asyncapi/modelina) will end up with unusable classes.
But this is an issue for all code generator where you are not owner of the schema.

There are 2 Issues:
- at the moment proper $id will only be generated by first level schemas. All sub schemas used in arrays or similar loose their name.
- For string enum the $id could be generated by the field name, if not set. 

I would suggest this to be enabled by an options to make it non breaking.

**Comment by magicmatatjahu** [comment]
Similar issue https://github.com/asyncapi/parser-js/issues/176

**Comment by jonaslagoni** [comment]
Just gonna leave a reference here: https://github.com/asyncapi/parser-api/issues/34

**Comment by GreenRover** [comment]
@jonaslagoni How can we get here any progress?

**Comment by jonaslagoni** [comment]
> @jonaslagoni How can we get here any progress?

Would be awesome if you want to take the lead in pushing this change @GreenRover, as I am not sure when I will be able to focus on it myself. 

We can set up a public meeting specifically for this if you want to? Or put it as part of a SIG meeting if you think that is more suiting? 🙂
