### ISSUE TITLE
Remove dist/bundle.js from the repo

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#530]
#### Reason/Context

`dist/bundle.js` was always there in the repo, but then we added release automation and it anyway is always available, fresh and nice on the release level, example: https://github.com/asyncapi/parser-js/releases/tag/v1.14.1

In other words: `bundle.js` is already available on a release level + npm package. 

Having it in the repo only causes confusion and continuous issues:
- with every single contribution as people commit it, then they have to remove it and it is causing headaches
- with long-living release branches that take months to release and in meantime bundle.js on master gets updated

**What do you think?**

cc @jonaslagoni @fmvilas @magicmatatjahu 

#### Description

We need to:
- remove `bundle.js` from this repo
- update readme information that `bundle.js` is also available on a release level
- add `bundle.js` to `.gitignore`
- update `package.json` to make sure `bundle.js` is an exception and that even though it is ignored, it should be pushed to npm

**Comment by magicmatatjahu** [comment]
Let's remove it.
