### ISSUE TITLE
Https, http, and path modules are not found, NX Angular

### ISSUE THREAD

**Issue by sarea** [asyncapi/parser-js#539]
When using @asyncapi/parser I got 3 errors about Https, http, and path 

```
./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js:3:13-28 - Error: Module not found: Error: Can't resolve 'http' in '/Users/user/project/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (/Users/user/project, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }

./node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js:4:14-30 - Error: Module not found: Error: Can't resolve 'https' in '/Users/user/project/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

./node_modules/@asyncapi/parser/lib/parser.js:3:13-28 - Error: Module not found: Error: Can't resolve 'path' in '/Users/user/project/node_modules/@asyncapi/parser/lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
```

I was also able to reproduce it here https://stackblitz.com/edit/typescript-uy7u9n?file=index.ts but the error is shown differently

**Comment by sarea** [comment]
Hi, any update here?

**Comment by magicmatatjahu** [comment]
@sarea Sorry for the delayed response. The problem you mentioned is related to the bundler rather than our package. The package uses `json-schema-ref-parser` library underneath and it uses the `http` and `https` modules and in some places also `path`. From what I understand you are using webpack 5, and they have removed the default fallbacks for nodejs modules in this version:

> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

You have to add polyfill yourself, for example here is one of the tutorials how to do it - https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5.

**Comment by sarea** [comment]
Thanks a lot @magicmatatjahu
I know about this solution, the thing is we use NX and Angular, and customizing the webpack configs is not as straightforward as mentioned, which makes it a really ugly workaround, and at least for me it did not work

So I thought that the same solution might be easier to apply on parser-js instead:D

**Comment by magicmatatjahu** [comment]
> So I thought that the same solution might be easier to apply on parser-js instead:D

How if we do not use any bundler (please don't consider browserify) in the repository?

**Comment by sarea** [comment]
@magicmatatjahu sorry for the late response, we use angular cli with nx which makes it really annoying to customize wepback config, I think it's also equally annoying for you too to fix it from your end, so I will close this issue.
