### ISSUE TITLE
[2.0.0] Add `schemaFormat` method to the Schema model

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/parser-js#544]
Check discussion about it https://github.com/asyncapi/parser-js/pull/542#discussion_r865652213

Probably in the `3.0.0` AsyncAPI we will move `schemaFormat` to the Schema Object - https://github.com/asyncapi/spec/issues/622

**Comment by smoya** [comment]
If we finally don't go on this, we should add the `schemaFormat` method to the message instead, which is missing even in the interface.

**Comment by magicmatatjahu** [comment]
Done in https://github.com/asyncapi/parser-js/pull/582
