### ISSUE TITLE
Dereference error does not include "title"

### ISSUE THREAD

**Issue by tim-lai** [asyncapi/parser-js#561]
#### Describe the bug

The dereferencing parser is not returning `definition.refs.title`, which is expected per [ParserError](https://github.com/asyncapi/parser-js/blob/master/API.md#module_@asyncapi/parser+ParserError).

#### How to Reproduce

1. Go to https://studio.asyncapi.com/
2. Introduce two `$ref` errors as seen in screenshot, e.g. line 32 and line 39.
3. Expand the `Problems` pane

![asyncapi-parser-deref-error](https://user-images.githubusercontent.com/12902658/172211366-e4789f77-a30e-4a78-85f5-b2b90803391e.png)

#### Expected behavior

In the screenshot, one can see that the title referencing line 39 is incorrect. It should be `Token "lightmeasured3" does not exist`.

This visual error is because `definition.title` is being used instead of `definition.refs[].title`, but more importantly is that I can observe that `definition.refs[].title` itself doesn't exist as an output of the parser.

**Comment by imabp** [comment]
Hey thanks for reporting that bug.
I could reproduce the error. I think, using the correct error index, will resolve the following issue. 

https://github.com/asyncapi/parser-js/blob/c962a7e7278f5fc8652621d8881032fceaa79a28/lib/parser.js#L162


@fmvilas, I was trying to solve the above issue. But I am blocked here, as I am unable to setup `parser-js` locally on my Apple MBP M1 Pro.  It returns an error. Do you have any workarounds for this?

<details>
<summary> Toggle to view error screenshot</summary>
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/53480076/178146887-249ef89b-185c-4156-8a85-864d90573602.png">

</details>

**Comment by magicmatatjahu** [comment]
It is resolved in the https://github.com/asyncapi/studio/pull/434
