### ISSUE TITLE
hasCircularProps no longer works for compositions

### ISSUE THREAD

**Issue by vennekilde** [asyncapi/parser-js#571]
#### Describe the bug
hasCircularProps stopped working correctly for compositions since parser v1.12.0

#### How to Reproduce

Tested using latest version of asyncapi/generator (1.9.5) with different version of asyncapi/parser using the following versions
- `npm install @asyncapi/parser@1.11.1` Works as expected
- `npm install @asyncapi/parser@1.12.0` Does not work as expected
- `npm install @asyncapi/parser@1.15.1` Does not work as expected

asyncapi.yaml
```yaml
asyncapi: 2.0.0
id: 'urn:dk:eurisco:go-a2s-generator'
info:
  title: go-a2s-generator test
  version: 1.0.0
  license:
    name: Proprietary
servers:
  development:
    url: localhost
    description: Development server
    protocol: nats
    protocolVersion: 2.2.1
defaultContentType: application/json
channels:
  publish:
    publish:
      message:
        $ref: '#/components/messages/recursive'
    bindings:
      nats:
        pubSub:
components:
  messages:
    recursive:
      name: All
      description: All payload properties in a single message
      payload:
        $ref: '#/components/schemas/recursive'
  schemas:
    recursive: 
      type: object
      properties:
        allOf: 
          $ref: '#/components/schemas/recursiveAllOf'
    recursiveAllOf:
      allOf:
        - $ref: '#/components/schemas/recursive'
        - type: object
          properties:
            string:
              type: string
```

`$$everySchema$$.txt`
```nunjucks
isCircular: {{schema.isCircular()}}
hasCircularProps: {{schema.hasCircularProps()}}
```

#### Expected behavior

`recursiveAllOf.txt` generated using v1.11.1
```
isCircular: false
hasCircularProps: true
```

#### Got behavior

`recursiveAllOf.txt` generated using v.1.15.1 and v1.12.0 which seems to have introduced the issue in https://github.com/asyncapi/parser-js/pull/391
```
isCircular: false
hasCircularProps: false
```

**Comment by magicmatatjahu** [comment]
@vennekilde I don't know why `hasCircularProps` implementation showed `true` for your case, but you should understand how `circular` schemas work. In your example you start "crawling" from `recursiveAllOf` schema:

`recursiveAllOf ` -> `allOf` -> `0 index` -> `recursive` (not circular) -> `properties ` -> `allOf` -> `0 index` (it's circular)

You should check circular/recursive schemas from POV of starting scheme because sometimes schema can be recursive, sometimes not. Also old implementation of  `hasCircularProps` function (< 1.12.0) had big issue due to fact that we operated on original object `recursiveAllOf` not on an internal copy, so bu this you had `true` not `false` -> it's information from original, not copied object.

**Comment by vennekilde** [comment]
The reason i don't find it useful, is that i would have to generate double the amount of structs for the following example

```yaml
components:
  messages:
    recursive1:
      name: Recursive1
      payload:
        $ref: '#/components/schemas/recursive1'
    recursive2:
      name: Recursive2
      payload:
        $ref: '#/components/schemas/recursive2'
  schemas:
    recursive1: 
      type: object
      properties:
          $ref: '#/components/schemas/recursive2'
    recursive2:
      type: object
      properties:
          $ref: '#/components/schemas/recursive1'
```

Using the viewpoint of only considering something recursive, if a recursion is reached will generated more code and the struct names will have to be differentiated which just makes me sad.

```golang
package messages 

type Recursive1 struct {
   Payload schemas.Recursive1_Recursive1
}

type Recursive2 struct {
   Payload schemas.Recursive2_Recursive2
}
```

```golang
package schemas 

type Recursive1_Recursive1 struct {
   Recursive2 Recursive1_Recursive2
}

type Recursive1_Recursive2 struct {
   Recursive1 *Recursive1_Recursive1 // Require pointer to avoid infinite allocation
}

type Recursive2_Recursive1 struct {
   Recursive2 *Recursive2_Recursive2 // Require pointer to avoid infinite allocation
}

type Recursive2_Recursive2 struct {
   Recursive1 Recursive2_Recursive1
}
```

Meanwhile, if i just check if they are every recursive, i can save the extra hassle and have reusable structs using pointers wherever there may be a recursion.

```golang
package messages 

type Recursive1 struct {
   Payload schemas.Recursive1
}

type Recursive2 struct {
   Payload schemas.Recursive1
}
```

```golang
package schemas 

type Recursive1 struct {
   Recursive2 *Recursive2 // Require pointer to avoid infinite allocation
}

type Recursive2 struct {
   Recursive1 *Recursive1 // Require pointer to avoid infinite allocation
}
```

**Comment by magicmatatjahu** [comment]
@vennekilde because you have such a case that the old solution made sense, and now imagine a recursion with an object having 10 fields and a recursion at level 5 or deeper. 

In addition, with current solution you can still render elements as you want (without hook).

**Comment by vennekilde** [comment]
Not sure why depth matters, is, it is still recursive.
The hook above should work on any level of recursion. When ever it can link a part of the chain in a recursive loop, it marks the whole chain section that is recursive from start to finish as recursive.

And yes, you can render elements as you want, but the problem is that pointers in my case, should ONLY be used, if the property is either recursive to itself to avoid infinite allocation, or is optional to allow nil allocation.

How would you mark a property as requiring pointer allocation, without having to check recursively, if it is required?

For reference, this is not allowed in golang. 
```golang
type Recursive1 struct {
   Recursive2 Recursive2 // Compilation error
}

type Recursive2 struct {
   Recursive1 Recursive1 // Compilation error
}
```
One of the properties has to be a pointer, or both, which i prefer due to neither being preferred over the other, as both are root schemas to a message, but i do not want to use pointers if not required, hence i need to know if it is recursive.

Btw, sorry for taking more of your time, but i want to understand how it could be done more efficiently, as it sounds like there is a better solution from your point of view.
