### ISSUE TITLE
Header other than object doesn't cause validation fail

### ISSUE THREAD

**Issue by derberg** [asyncapi/parser-js#68]
#### Describe the bug
Header other than object doesn't cause validation fail. It is probably the same not only in `message` but also `messageTrait`

#### How to Reproduce
Try below file in playground and you'll see no errors even though the spec clearly says that `headers` must be `object` of type

```json
{
      "asyncapi": "2.0.0",
      "info": {
          "title": "Valid AsyncApi document",
          "version": "1.0"
      },
      "channels": {},
      "components": {
          "messages": {
              "userSignUp": {
                  "summary": "Action to sign a user up.",
                  "description": "Multiline description of what this action does.\nHere you have another line.\n",
                  "tags": [{
                          "name": "user"
                      },
                      {
                          "name": "signup"
                      }
                  ],
                  "headers": {
                      "type": "integer",
                      "enum": [1, 2]
                  },
                  "payload": {
                      "type": "integer"
                  }
              }
          }
      }
  }
```

#### Expected behavior
Parser should throw error that header must be of `object` type

**Comment by derberg** [comment]
Spec about headers: `Schema MUST be of type "object"` but it also states that this parameter is of type ref or https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#schemaObject and therefore schema also refs to schema definition https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L642-L643

This is why parser doesn't see an issue but it is a problem with the schema and not the parser.

@fmvilas any directions appriciated?  For me it is a bug in the spec

**Comment by fmvilas** [comment]
It sounds like a bug here: https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L642-L643. It should have this rule + enforce its type is "object". Something like:

```json
"headers": {
  "allOf": [
    { "$ref": "#/definitions/schema" },
    {
      "type": "object",
      "required": ["type"],
      "properties": {
        "type": "object"
      }
    }
  ]
}
```
