### ISSUE TITLE
Add constructor type

### ISSUE THREAD

**Issue by airamrguez** [asyncapi/parser-js#728]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@asyncapi/parser@1.18.1` for the project I'm working on.

I think the `constructor` should also be specified in the `d.ts` file.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@asyncapi/parser/types.d.ts b/node_modules/@asyncapi/parser/types.d.ts
index 2da37a4..d1f7dd2 100644
--- a/node_modules/@asyncapi/parser/types.d.ts
+++ b/node_modules/@asyncapi/parser/types.d.ts
@@ -291,6 +291,7 @@ declare module "@asyncapi/parser" {
      * Implements common functionality for all the models.
      */
     class Base {
+        constructor(json: any);
         /**
          * @param [key] - A key to retrieve from the JSON object.
          */
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by derberg** [comment]
Good catch. Can you open up a PR to fix that? but not directly in types file but in https://github.com/asyncapi/parser-js/blob/master/lib/models/base.js through JSDocs, as `d.ts` file is generated from it
