### ISSUE TITLE
Add request/reply support  

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#732]
#### Reason/Context

Request/reply has finally been merged as of https://github.com/asyncapi/spec/pull/847.

Now it's time to add support for it in the parser, in the `next-major-spec´ branch.

We might have to do some changes to the parser API as well 🤔 cc @magicmatatjahu @smoya do you have a clear overview here?

**Comment by GreenRover** [comment]
What is the correct base branch for 3.0 features?

**Comment by jonaslagoni** [comment]
This one: https://github.com/asyncapi/parser-js/tree/next-major-spec

**Comment by magicmatatjahu** [comment]
Part of request/reply is added in this PR https://github.com/asyncapi/parser-js/pull/708 We can merge it and add missed part in another PR.

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/parser-js/pull/745
