### ISSUE TITLE
Message headers .json() shouldn't have 'x-parser-schema-id' property

### ISSUE THREAD

**Issue by ClearEyesFullHearts** [asyncapi/parser-js#743]
#### Describe the bug
The result of the .json() function on the headers leave 'x-parser-schema-id' properties on the object.

#### How to Reproduce
@asyncapi/parser: v1.18.1
asyncapi file version: v2.6.0

```javascript
const parser = require('@asyncapi/parser');
const fs   = require('fs');

async function my() {
    // use the kafka template asyncAPI file from the studio
    const doc = fs.readFileSync('./kafka-template.yaml', 'utf8')
    const api = await parser.parse(doc);

    const channel = api.channel('smartylighting.streetlights.1.0.event.{streetlightId}.lighting.measured');
    const operation = channel.publish();
    const message = operation.message();
    const headers = message.headers();
    console.log('json', headers.json());
}

my();
```
Result is:
```
json {
  type: 'object',
  properties: {
    'my-app-header': {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      'x-parser-schema-id': '<anonymous-schema-2>'
    }
  },
  'x-parser-schema-id': '<anonymous-schema-1>'
}
```

#### Expected behavior
```
json {
  type: 'object',
  properties: {
    'my-app-header': {
      type: 'integer',
      minimum: 0,
      maximum: 100
    }
  }
}
```

**Comment by derberg** [comment]
Hey @ClearEyesFullHearts 

We depend in parser a lot on `x-parser-` extensions: https://github.com/asyncapi/parser-js#custom-extensions

Simples example is in https://github.com/asyncapi/parser-js/blob/master/lib/models/asyncapi.js#L47

in other tools we are just ignoring and hiding in UI stuff that starts with `<anonymous` or field starts with `'x-parser-'`

**Comment by ClearEyesFullHearts** [comment]
Hey @derberg 

Thanks for the answer. So if i understand correctly it's normal for the ".json()" function to return the 'x-parser-xxx' properties because it's used internally, right?
Is there a way to get the clean json object then? For messages we can use ".originalPayload()", is there something like that for the other objects?
I think it's quite important to be able to access this information, at least for the schema objects, so that we can feed it to a validator, like ajv for example, without further transformation.

Regards,

**Comment by smoya** [comment]
> @smoya can you share how it works in parser 2.0?

Parser-js v2.0.0 follows the same behavior:

```js
import { Parser, fromURL } from '@asyncapi/parser'; // this

const kafkaExampleURL = 'https://raw.githubusercontent.com/asyncapi/spec/master/examples/streetlights-kafka.yml';
const parser = new Parser();
const { document } = await fromURL(parser, kafkaExampleURL).parse();

if (document) {
  const headers = document.channels().get('smartylighting.streetlights.1.0.event.{streetlightId}.lighting.measured').messages()[0].headers();
  console.log(headers.json());
}
```

Output:

```js
{
  type: 'object',
  properties: {
    'my-app-header': {
      type: 'integer',
      minimum: 0,
      maximum: 100,
      'x-parser-schema-id': '<anonymous-schema-2>'
    }
  },
  'x-parser-schema-id': '<anonymous-schema-1>'
}
```

**Comment by derberg** [comment]
yeah, which makes sense, especially that we need it inside parser

alternative solution could be another API function or an argument for `json()` function that would bring output without `x-parser` props 🤔

**Comment by smoya** [comment]
> yeah, which makes sense, especially that we need it inside parser
> 
> alternative solution could be another API function or an argument for `json()` function that would bring output without `x-parser` props 🤔

A new function in `utils.ts` or similar that cleanups extensions and additions. The point is how references will be then showed? Should we put back the JSON pointer line or rather keep the unreferenced object? 🤔 
Maybe not that trivial as thought but of course, possible to do.

**Comment by derberg** [comment]
but addition of `x-parser` extensions happens after dereferencing. They should stay there in the object. We just need a helper function on each model that enable you get object without these technical extensions

**Comment by smoya** [comment]
> but addition of `x-parser` extensions happens after dereferencing. They should stay there in the object. We just need a helper function on each model that enable you get object without these technical extensions

That's right. I was thinking on how the expected behaviour would feel right for @ClearEyesFullHearts. Like expecting the really original object (like including JSON Pointer). But that's not even possible because indeed we dereference before as you perfectly stated, so 👍 to add such a cleanup function as a short term solution.
