### ISSUE TITLE
Implement support for $ref in security object

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/parser-js#746]
The implementation of https://github.com/asyncapi/spec/pull/852 is missing here.

It should be just a matter of adding `$ref` support in the Server's `security` object, renaming `scopes` (OAuth Flow) to `availableScopes`, and adding `scopes` to the Security Scheme Object.

**Comment by magicmatatjahu** [comment]
It's implemented here https://github.com/asyncapi/parser-js/pull/708
