### ISSUE TITLE
[2.0.0] `convertToOldAPI` signature issue

### ISSUE THREAD

**Issue by smoya** [asyncapi/parser-js#751]
#### Describe the bug
First, it seems the example of how to use the `convertToOldAPI` is wrong in the [README](https://github.com/asyncapi/parser-js/tree/next-major#convert-to-the-old-api). It is not exported under `'../src/parser` but `'../src/old-api/converter'`

Also, it seems the signature of the method is incorrect.

#### How to Reproduce
When trying to convert a document to the old API, the following error appears: 

```
Argument of type 'AsyncAPIDocumentInterface | undefined' is not assignable to parameter of type 'AsyncAPIDocumentInterface'.
  Type 'undefined' is not assignable to type 'AsyncAPIDocumentInterface'.
```

#### Expected behavior
The converter should work.

**Comment by magicmatatjahu** [comment]
> First, it seems the example of how to use the convertToOldAPI is wrong in the [README](https://github.com/asyncapi/parser-js/tree/next-major#convert-to-the-old-api). It is not exported under '../src/parser but '../src/old-api/converter'

What? You have proper export. https://github.com/asyncapi/parser-js/blob/next-major/src/index.ts#L13

`document` from `parse()` function can be undefined. Signature is good, but there's not condition to check if document exists - if you think that it should be checked, please create PR.

**Comment by smoya** [comment]
You are right. Really I don't understand what I did wrong 😓
