### ISSUE TITLE
Message object name in channelItemObject message.ref field cannot contain whitespaces

### ISSUE THREAD

**Issue by DharinaHanumunthadu** [asyncapi/parser-js#753]
#### Describe the bug
AsyncAPI document fails to parse on AsyncAPI studio when the `message.$ref` field in the `channelItemObject` contains a reference to a message object in which its name contains spaces, as opposed to being camel-cased.

Note that the schema object names on the other hand work fine with spacing in them when referenced in a message object.

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

Test File with bug: [testFile.csv](https://github.com/asyncapi/parser-js/files/11262850/testFile.csv)

1. Copy paste the attached file contents into AsyncApi Studio
2. There are 2 diagnostic errors that show up (`Referencing in this place is not allowed`), on line 44 and 54

Screenshot: 
![Screen Shot 2023-04-18 at 10 27 11 AM](https://user-images.githubusercontent.com/65047413/232808605-d617c6c9-4bfd-4aa4-ae47-022f747a3206.png)

Slack thread: https://asyncapi.slack.com/archives/C0230UAM6R3/p1681763680898089 

#### Expected behavior
Expect the message object with name `turn OnOff` to be referenced without validation issues in `message.$ref: '#/components/messages/turn OnOff'` on lines 44 and 54

**Comment by darrylmacrae** [comment]
Is there a plan to address this issue in AsyncAPI v2 or v3 ?

**Comment by AayushSaini101** [comment]
I don't think so, we need  to allow the spacing in the statements of the references
