### ISSUE TITLE
Support resolution of refs which require authentication

### ISSUE THREAD

**Issue by bjhartin** [asyncapi/parser-js#771]
#### Reason/Context

- Why we need this improvement?

Some HTTP resources require authentication, especially in corporate environments.

- How will this change help?

This change will allow refs to point to resources which might be behind authentication.  When we want to extract common schema elements, e.g. create a schema registry, this becomes important.  In corporate environments its common for repositories (of various kinds) to require authentication.

- What is the motivation? 

To enable the use of schema registries to DRY up contracts that contain repetition.

#### Description

- What changes have to be introduced?

refs need to support authentication headers - perhaps through the existing servers mechanism.

- Will this be a breaking change?

No.

- How could it be implemented/designed?

I think it's pretty straightforward with the main question being where the authentication is configured.

**Comment by bjhartin** [comment]
I assume a change to the actual standard would take some time, but perhaps the generator could support this in a way that doesn't require a change to the standard, e.g. perhaps it could accept configuration that is logically the same as:

```json
[{
  "domain": "x.y.z",
  "authType": "Bearer token",
  "token value": "..."
}, ...]
```

Which I could pass in in my CI pipeline, where the token value is exposed as a secret.

**Comment by bjhartin** [comment]
Related issue I've opened with OpenAPI: https://github.com/OAI/OpenAPI-Specification/issues/3270

**Comment by derberg** [comment]
There is a related issue, just ssl related https://github.com/asyncapi/parser-js/issues/207

Tooling supports custom resolvers. We just need someone willing to contribute and we also need a way on how someone should specify authorization details through the `options` object. And then we can also use it in generator, cli and other tools (we will just have to enable in these tools providing more sophisticated configuration options)
