### ISSUE TITLE
AsyncAPI spec v3 support in parser-js

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#780]
### Reason/Context
This Issue is used to track changes to the parser needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

### Scope

- [x] Add v3 models
- [x] Multi-format support https://github.com/asyncapi/parser-js/pull/785
- [x] Apply new traits behavior
- [ ] #801

**Comment by smoya** [comment]
I'm taking over `Add v3 models`

**Comment by jonaslagoni** [comment]
Closing as the newest release of the parser contains support for v3 in the basic form and we have individual issues to track further support
