### ISSUE TITLE
Possible inconsistence between isEmpty and pop in Channels class (V2)?

### ISSUE THREAD

**Issue by adalbertocajueiro** [asyncapi/parser-js#792]
#### Describe the bug
I have faced a small problem when obtaining the the channels interface from a specification (spec.allChannels()). It returns a ChannelsInterface object which extends Collection which extends Array. When invoking method pop() the state change occurs as expected. However, if we remove all elements through many pop() invocations, the methods isEmpty() does not returns true because it checks the length of the internal collection field, instead of the elements (in the array sense).  Is this a consistence problem or I'm using methods wrongly?

#### How to Reproduce
Steps to reproduce the issue. Attach all resources that can help us understand the issue:

- Load the content of an asyncapi specification containing channels into a variable content
- Obtain the APIDocument by parsing the content: var parsedObject = parse.parse(content)
- Get the channels: var channels = parsedObject.document.allChannels()
- test the code to check if it has an infinite loop:
while(this.channels!.isEmpty() > 0){
      this.channels?.pop()
}

#### Expected behavior
channels becomes clear and the above loop stops. I have changed the use of .isEmpty() by .length and everything worked.

**Comment by smoya** [comment]
Is this still valid? We should definitely test it.

**Comment by adalbertocajueiro** [comment]
Hi smoya. You can close this issue, please. Instead of traversing the asyncapi object I moved to use the asyncapi/parser tool, which is not affected by it. Many thanks.
