### ISSUE TITLE
"messageId" must be unique across all the messages.

### ISSUE THREAD

**Issue by wiegell** [asyncapi/parser-js#793]
### Describe the bug
One message cannot be reused in publish and subscribe in the same channel, if a messageId is defined on the message

### To Reproduce

0. Assume someMessage has messageId defined.
1. Create a document with a channel like so:
```
channels:
  someChannel:
    publish:
      message:
        $ref: "#/components/messages/someMessage"
    subscribe:
      message:
        $ref: "#/components/messages/someMessage"
    bindings:
      eventstore:
        # This is not autogenerated to go code unfortunately
        streamName: "someStream"
```
2. Try to `asyncapi generate models golang`
3. See error `error  asyncapi2-message-messageId-uniqueness  "messageId" must be unique across all the messages.`

### Expected behavior
This should be possible. My usecase is that i want the same service to publish and subscribe to the same eventstore channel, that is used to persist data

**Comment by derberg** [comment]
@smoya @jonaslagoni 

- any idea why missing `messageId` is popping up as warning? it is optional field
- I think the point @wiegell brought makes sense. The thing is that we probably use spectral validation after dereferencing, so spectral sees duplicated inlined message. That should be changed, right? same about `operationId` I guess, when people will start reusing operations 🤔

**Comment by jonaslagoni** [comment]
> any idea why missing messageId is popping up as warning? it is optional field

Because spectral rules have been set up to do so 🤷 If you need more information I gotta tag @magicmatatjahu in 😄 

> I think the point @wiegell brought makes sense. The thing is that we probably use spectral validation after dereferencing, so spectral sees duplicated inlined message. That should be changed, right? same about operationId I guess, when people will start reusing operations 🤔

Yep, it's a bug.

**Comment by magicmatatjahu** [comment]
Yes, missed `messageId` is treated as warning because it's a good design pattern to define it, in CLI (as ai remember) you can disallow all warnings. And for the second thing, it's a bug. Spectral rule should check the messageId by the message references, not by inline value.

**Comment by smoya** [comment]
> Spectral rule should check the messageId by the message references, not by inline value.

But that's not possible with the current dereferencing strategy, isn't it? Spectral resolves references and then validate.

IIRC, we do create our own reference Resolver that later inject to Spectral options. Would it make sense we do add a new internal field to the `MessageObject` where we store a variation of the `messageId` like adding a suffix so we can later validate uniqueness based on that?

Using the previous example, the resolver will resolve `#/components/messages/someMessage`, and inject a new field called `_IdToCompare` (we need to choose a proper name) and then use that, in the case Is present, during validation?

WDYT @magicmatatjahu? Maybe there is a simpler approach but it scapes from my knowledge then.

**Comment by magicmatatjahu** [comment]
There should be a possibility to check the references (I mean the dereferenced messages) by the reference in JS memory, so comparison of two messages which are references from this same reference should be equal `true`. `json-schema-ref-parser` works in that way, I don't remember if Spectral resolver also.

**Comment by smoya** [comment]
@wiegell would you like to work on the fix considering the suggested solutions @magicmatatjahu posted? We can bring you assistance if you need it.

**Comment by wiegell** [comment]
Thank you for the confidence, but i don't have the time atm. Also the messageId is not vital to my current project. Out of curiosity: does any of the code generators transpile the messageId into one of the destination languages? In go i only get the schema structs.

**Comment by Gilles-qbmt** [comment]
I had the same issue when trying to generate code with the async-api generator. 

I used a file template: $$message$$.java and the code uses the messageId. If the messages have a messageId it errors with not unique and when not specified the generator always outputs a single undefned.java file.

As a workaround I use "x-parser-message-name" on the messages since this is a fallback for the id field.
