### ISSUE TITLE
Native JS Parser: Encapsulate access to AsyncAPI

### ISSUE THREAD

**Issue by rmelian** [asyncapi/parser-js#8]
it’d be great to think about the API to retrieve useful information without having to know the structure of the document

something like .getMessages, getServers, getChannels, etc…

The idea is that, if at some point there’s a breaking change in the spec, the `.getMessages` call (for example) remains the same.

**Extracted from a conversation with @fmvilas**

**Comment by fmvilas** [comment]
Starting work on this issue.
