### ISSUE TITLE
Cannot access operation reply information

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#831]
#### Describe the bug
In the v3 operation model you have access to `operation.reply()` however in the parser API you don't have access to this.

**Comment by smoya** [comment]
Just to clarify, the [Parser-API](https://github.com/asyncapi/parser-api/pull/86/files#diff-ac35ac6e0b0ad3629802a0e04076aa18e94da614f5392e1164dcaacdfe3ee198R302) is correct but [the implementation of the interface in Parser-JS](https://github.com/asyncapi/parser-js/blob/next-major-spec/src/models/operation.ts) is not.
