### ISSUE TITLE
Traits break comparisons and calls for v3 and v2

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-js#856]
#### Describe the bug
I only have one concrete instance to show for here, but I bet it applies to other places as well.

#### How to Reproduce
With the following example https://github.com/asyncapi/spec/blob/next-major-spec/examples/streetlights-kafka.yml

And if you iterate over operations and want to find the associate channel for the operation:
```
operations.forEach(operation => {
    const channel = operation.channels().all()[0];
    // Channel is always undefined when traits are used
    ...
```

It will always fail to find the channel if traits have been applied. The problem is the following line: https://github.com/asyncapi/parser-js/blob/1fa12408a13b058d5fee02abbe7bd0cb0a4f9171/src/models/v3/operation.ts#L52

An example would be, `channel` would hold the value:
```
{
  address: "smartylighting.streetlights.1.0.event.{streetlightId}.lighting.measured",
  messages: {
    "receiveLightMeasurement.message": {
      headers: {
        type: "object",
        properties: {
          "my-app-header": {
            type: "integer",
            minimum: 0,
            maximum: 100,
            "x-parser-schema-id": "<anonymous-schema-3>",
          },
        },
        "x-parser-schema-id": "<anonymous-schema-2>",
      },
      name: "lightMeasured",
      title: "Light measured",
      summary: "Inform about environmental lighting conditions of a particular streetlight.",
      contentType: "application/json",
      traits: [
        {
          headers: {
            type: "object",
            properties: {
              "my-app-header": {
                type: "integer",
                minimum: 0,
                maximum: 100,
                "x-parser-schema-id": "<anonymous-schema-25>",
              },
            },
            "x-parser-schema-id": "<anonymous-schema-24>",
          },
        },
      ],
      payload: {
        type: "object",
        properties: {
          lumens: {
            type: "integer",
            minimum: 0,
            description: "Light intensity measured in lumens.",
            "x-parser-schema-id": "<anonymous-schema-5>",
          },
          sentAt: {
            type: "string",
            format: "date-time",
            description: "Date and time when the message was sent.",
            "x-parser-schema-id": "<anonymous-schema-6>",
          },
        },
        "x-parser-schema-id": "<anonymous-schema-4>",
      },
    },
  },
  description: "The topic on which measured values may be produced and consumed.",
  parameters: {
    streetlightId: {
      description: "The ID of the streetlight.",
    },
  },
}
```

and `this._json.channel` would contain:

```
{
  address: "smartylighting.streetlights.1.0.event.{streetlightId}.lighting.measured",
  messages: {
    "receiveLightMeasurement.message": {
      name: "lightMeasured",
      title: "Light measured",
      summary: "Inform about environmental lighting conditions of a particular streetlight.",
      contentType: "application/json",
      traits: [
        {
          headers: {
            type: "object",
            properties: {
              "my-app-header": {
                type: "integer",
                minimum: 0,
                maximum: 100,
                "x-parser-schema-id": "<anonymous-schema-25>",
              },
            },
            "x-parser-schema-id": "<anonymous-schema-24>",
          },
        },
      ],
      payload: {
        type: "object",
        properties: {
          lumens: {
            type: "integer",
            minimum: 0,
            description: "Light intensity measured in lumens.",
          },
          sentAt: {
            type: "string",
            format: "date-time",
            description: "Date and time when the message was sent.",
          },
        },
      },
    },
  },
  description: "The topic on which measured values may be produced and consumed.",
  parameters: {
    streetlightId: {
      description: "The ID of the streetlight.",
    },
  },
}
```

Which should return true in comparison, however it will never happen because the underlying json are different because the parser applied traits, and in theory the extensions as well.

**Comment by smoya** [comment]
In fact, tests are wrong... https://github.com/asyncapi/parser-js/blob/next-major-spec/test/custom-operations/apply-traits-v3.spec.ts#L59

**Comment by jonaslagoni** [comment]
/progress 10 started to look into this...

**Comment by jonaslagoni** [comment]
/progress 25 starting to get a hang of it and the different solutions, still need to figure out the best approach.

**Comment by smoya** [comment]
Do not take this as a proper answer. I need more time to refresh the whole workflow for parsing and applying custom ops, etc. Only then, I will come back and give you a better answer and hopefully help taking a decision. 

In one side, `Unifying the underlying JSON` seems like something I would expect to behave by default. If there is no strong reason to keep different versions of "same" object, I see then no reason to keep it in that way then. 
cc @magicmatatjahu you have all the historical knowledge on that side, would you mind helping us clarifying this? Just in case there is some use case we are missing.

About the unique ID thing, I tried to find an old discussion we had somewhere in an issue where we discussed just a bit about that concept; to have that uid in all objects so we could compare. I would like to remember what were the caveats but I can't. I think @magicmatatjahu shared them as well 🤔

**Comment by jonaslagoni** [comment]
/progress 40 problem + potential solutions have been found, waiting on further feedback.

**Comment by jonaslagoni** [comment]
/progress 50 started working on the implementation and adding tests to ensure it works long term

**Comment by jonaslagoni** [comment]
Already fixed in https://github.com/asyncapi/parser-js/pull/910
