### ISSUE TITLE
[v3] Implement custom schema parsing

### ISSUE THREAD

**Issue by smoya** [asyncapi/parser-js#859]
#### Describe the bug
I found out the following commented code https://github.com/asyncapi/parser-js/blob/next-major-spec/src/custom-operations/index.ts#L44-L47.

That means the call to `parse()` on custom schema parsers (Avro, OpenAPI, etc) is not being called for v3. That means schemas with those schema formats are never parsed. It also means users and tools won't be able to access to the transformed schema (we transform all of them to AsyncAPI Schema).

#### Expected behavior
The call to `parse` should be implemented.

cc @magicmatatjahu

**Comment by magicmatatjahu** [comment]
It wasn't implemented because we had to wait to final version of schemas (exactly multiple schemas) in v3

**Comment by smoya** [comment]
This is then completely critical and requires to be implemented for the next release, otherwise schemas with a schema format different than AsyncAPI one won't be parsed, meaning raw schemas will be in place.

**Comment by jonaslagoni** [comment]
/progress 90 finished and ready to be reviewed

**Comment by jonaslagoni** [comment]
Done in https://github.com/asyncapi/parser-js/pull/864
