### ISSUE TITLE
Inconsistence Parser Methods 

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/parser-js#884]
When using the Parser package, I noticed, for example, in the [Parser-api](https://github.com/asyncapi/parser-api/blob/master/docs/api.md) docs, the `Channel` section includes more methods that are not available in the Parser, E.g. hasSummary(). 

The following issue also brings about a new observation, why do we have a `.channels()` method in operation, when we can only have a single channel per operation? Isn't it supposed to be `operation.channel()`?

**Comment by jonaslagoni** [comment]
Because the parser API is an abstraction on top of the AsyncAPI structure. So it will never be 1-to-1 representation of the spec 🙂

Read more here: https://github.com/asyncapi/parser-api
