### ISSUE TITLE
Parser fails to return Operation Channel

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/parser-js#891]
#### Describe the bug
When I apply a list of traits to the operation object and try to retrieve the operation channel, the parser fails to return the channel

#### How to Reproduce
Apply a list of traits to an operation object and try retrieving the operation channel. `operation.channels().all()[0]`

Here's an example you can test it against https://raw.githubusercontent.com/asyncapi/spec/next-major-spec/examples/streetlights-kafka-asyncapi.yml

#### Expected behavior
The parser should return the operation channel in as much as the channel exists 

cc @smoya @derberg @jonaslagoni

**Comment by jonaslagoni** [comment]
Duplicate of https://github.com/asyncapi/parser-js/issues/856 🙂
