### ISSUE TITLE
Parser fails to return Operation

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/parser-js#900]
#### Describe the bug
When trying to retrieve the list of Operations, Parser fails to return Operations with `traits`

#### How to Reproduce
add traits to any of your Operations, and try retrieving the list of Operations available 

![AsyncApi-React-Playground-App (3)](https://github.com/asyncapi/parser-js/assets/40604284/eb96868b-62e9-4441-9f4f-7b3ae5d87fa0)

example file: https://raw.githubusercontent.com/asyncapi/spec/next-major-spec/examples/streetlights-kafka-asyncapi.yml

#### Expected behavior
The parser should return the list of Operations available 

cc @smoya

**Comment by jonaslagoni** [comment]
This is gonna be solved by solving https://github.com/asyncapi/parser-js/issues/856, using it for triage.
