### ISSUE TITLE
Types for typescript?

### ISSUE THREAD

**Issue by johndcarmichael** [asyncapi/parser-js#93]
When using this tool programmatically within a typescript app, I could not see any type definitions anywhere.. are there any in the pipelines or an @types package i might have missed?

**Comment by derberg** [comment]
Hi @johndcarmichael. I don't have much experience with TypeScript. Parser is pure JS but the models have pretty good jsdoc, maybe these could be used to genereate types? there are some tools https://github.com/otris/jsdoc-tsd.

No one is working on it at the moment, and full focus is on 1.0 release and as high coverage of spec validation as possible.

**Comment by magicmatatjahu** [comment]
Maybe `ts-types` repository would be great for this approach. Repo only with TS types with types helpers in guards form https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types.

In free time I tried to create types from JSON Schema spec by https://github.com/bcherny/json-schema-to-typescript lib, but it return trashed types in some places like:

```ts
export type Message =
  | Reference
  | (
      | {
          oneOf: Message[];
        }
      | {
          schemaFormat?: string;
          contentType?: string;
          headers?: Schema & {
            type?: {
              [k: string]: unknown;
            };
            [k: string]: unknown;
          };
          payload?: unknown;
          correlationId?: Reference | CorrelationId;
          tags?: Tag[];
          /**
           * A brief summary of the message.
           */
          summary?: string;
          /**
           * Name of the message.
           */
          name?: string;
          /**
           * A human-friendly title for the message.
           */
          title?: string;
          /**
           * A longer description of the message. CommonMark is allowed.
           */
          description?: string;
          externalDocs?: ExternalDocs;
          deprecated?: boolean;
          examples?: {
            [k: string]: unknown;
          }[];
          bindings?: BindingsObject;
          traits?: (
            | Reference
            | MessageTrait
            | []
            | [Reference | MessageTrait]
            | [
                Reference | MessageTrait,
                {
                  [k: string]: unknown;
                }
              ]
          )[];
          [k: string]: SpecificationExtension;
        }
    );
```

Also https://app.quicktype.io/ has also a problem with generating types.

At the moment I have a full spec written in TS, without Bindings.

@derberg @fmvilas @jonaslagoni What do you think guys?

**Comment by jonaslagoni** [comment]
Isn't this issue regarding missing types package for the parser itself? (not the spec)

I added types for the generator, which was done with JSDoc to automatically generate the types, thinks that's the way to do here as well :) Think I used https://www.npmjs.com/package/tsd-jsdoc

**Comment by magicmatatjahu** [comment]
@jonaslagoni Yes, this issue is related to parser, but I wonder if an idea with a separate package with only types would be a good one.

**Comment by jonaslagoni** [comment]
@magicmatatjahu I am unsure of the use-case specifically in this context. Are you talking about making a repository containing types from the spec it self and use that to somehow solve this issue? 🤔 

Cause with tsd-jsdoc we can have 0 maintaining from our side and generate it with github actions, which I think would be perfect fit which requires a minimal effort to solve from the maintainer point of view 😄

**Comment by johndcarmichael** [comment]
I think tsd-jsdoc is the better solution here as will be published and up to date with each release of this package. The @types namespace on npm i think was originally intended to give typescript more appeal when i was originally launched as no packages had types defined and waiting for the original authors to react would be too slow.

**Comment by jonaslagoni** [comment]
> Is tsd-jsdoc something you will be publishing with this tool any time soon @jonaslagoni ?

@johndcarmichael unless @magicmatatjahu wants to take it for a spin. As long as there are no complications with the current jsdoc implementation it shouldn't take long 😄

**Comment by magicmatatjahu** [comment]
@jonaslagoni I don't have any objections with using `tsd-jsdoc`.If it makes maintenance code easier, it's ok to me.

**Comment by jonaslagoni** [comment]
@johndcarmichael PR is up, can you review it and ensure it works as you would expect 😄

**Comment by johndcarmichael** [comment]
Awesome! Thanks for the types guys, will work the new parser into boats and delete the ignore lints and custom unique opid checks :+1:
