### ISSUE TITLE
Missing externalDocs on Schema Object

### ISSUE THREAD

**Issue by jcmellado** [asyncapi/parser-js#95]
#### Reason/Context
The Schema Object specification has an `externalDocs` field:
https://www.asyncapi.com/docs/specifications/2.0.0/#schemaObject

But that field is missing from the Schema model:
https://github.com/asyncapi/parser-js/blob/master/API.md#Schema

#### Description
Add `externalDocs()` method to the Schema model.

**Comment by derberg** [comment]
@jcmellado thanks for reporting this one, you want to work on it? I see you need it in the markdown template

**Comment by jcmellado** [comment]
@derberg https://github.com/asyncapi/parser-js/pull/97
