### ISSUE TITLE
Message traits are not applied when using oneOf on channels

### ISSUE THREAD

**Issue by jcmellado** [asyncapi/parser-js#96]
#### Describe the bug
Message traits are not applied when using `oneOf` on channels.

#### How to Reproduce
Using the following code for testing:

```js
const asyncapi = await parser.parse(<FILE>);
  
const result = asyncapi.channels()['test'].subscribe().messages()[0].contentType();
```

I get the expected result (`contentType: application/json`) with the following YAML file:

```yaml
asyncapi: 2.0.0

info:
  title: Test
  version: 1.0.0

channels:
  test:
    subscribe:
      message:
        $ref: "#/components/messages/test"

components:
  messages:
    test:
      payload:
        type: string
      traits:
        - $ref: "#/components/messageTraits/commons"

  messageTraits:
    commons:
      contentType: application/json
```

But I get the wrong result (`contentType: undefined`) with the following YAML file:

```yaml
asyncapi: 2.0.0

info:
  title: Test
  version: 1.0.0

channels:
  test:
    subscribe:
      message:
        oneOf:
          - $ref: "#/components/messages/test"

components:
  messages:
    test:
      payload:
        type: string
      traits:
        - $ref: "#/components/messageTraits/commons"

  messageTraits:
    commons:
      contentType: application/json
```

I have tried with more than one message, and other traits, like headers, but they are missing from the message too.

#### Expected behavior
Message traits should be applied.

**Comment by derberg** [comment]
@jcmellado thanks for reporting it will well written examples. Application of traits happens here https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L196 so we need to investigate what happens there

**Comment by jcmellado** [comment]
I think that this issue is caused by this function:
https://github.com/asyncapi/parser-js/blob/master/lib/parser.js#L150

Relevant source code:
```
        if (options.applyTraits) {  
          applyTraits(op);
          applyTraits(op.message); // <=== maybe it should inspects here if oneOf is set
        }
        
        const msg = op.message; // <=== same here
        if (msg) await validateAndConvertMessage(msg);
```

I'm still not feeling very confident with the source code to file a pull request.

**Comment by magicmatatjahu** [comment]
@jcmellado Hello. I fixed bug in https://github.com/asyncapi/parser-js/pull/108 PR.
